# Global Justfile Owner (~/.config/just/justfile)
#
# Concatenates `cc` recipes from claude.nix and `cx` recipes from codex.nix
# into the single global justfile. Owns the shared header (`set shell := …`).
#
# Why a separate module: claude.nix and codex.nix each generate their own
# recipe text from their own SSOT, but only one module can write a given file
# in home-manager. This module is the single owner.
{
  config,
  lib,
  ...
}:
let
  inherit (lib) concatStringsSep mkEnableOption mkIf;

  ccRecipes = config.modules.home.apps.mcp.ccJustRecipes or "";
  cxRecipes = config.modules.home.apps.codex.cxJustRecipes or "";
  cxNetRecipes = config.modules.home.apps.codex.cxNetJustRecipes or "";

  sharedHeader = concatStringsSep "\n" [
    "# Global Justfile (just -g <recipe>)"
    "# Generated by Nix from modules/home/apps/agents-launcher.nix."
    "# Recipe sources:"
    "#   cc / cc-status        → modules/home/apps/claude.nix (accountDefs)"
    "#   cx / cx-status        → modules/home/apps/codex.nix (codexAccountDefs)"
    "#   cx-net / cx-net-creds → modules/home/apps/codex.nix (codexAccountDefs, CC-94)"
    ""
    ''set shell := ["bash", "-euo", "pipefail", "-c"]''
    ""
  ];

  combined = sharedHeader + ccRecipes + "\n" + cxRecipes + "\n" + cxNetRecipes;
in
{
  options.modules.home.apps.agentsLauncher = {
    enable = mkEnableOption "Global justfile aggregator for cc + cx multi-account launchers";
  };

  config = mkIf config.modules.home.apps.agentsLauncher.enable {
    xdg.configFile."just/justfile".text = combined;
  };
}
