# Claude Code Single Source of Truth
# Generates: MCP servers, plugins, marketplaces for Claude Desktop AND Code CLI
#
# ARCHITECTURE (January 2026 - MINIMAL):
# - Claude Desktop: Reads ~/Library/Application Support/Claude/claude_desktop_config.json
#   → Generated by Nix activation hook (Electron app needs PATH injection)
# - Claude Code CLI: Reads ~/.claude.json
#   → Generated by Nix activation hook (merges with runtime state via jq)
# - nix-config.json: Plugins/marketplaces for TypeScript to consume
#
# Configuration (April 2026):
# - 1 MCP server (ref) — Linear via /linear skill (GraphQL API)
# - 1 plugin (caveman) — terse output, token savings
# - 1 extra marketplace (JuliusBrussee/caveman)
# - 1 DXT extension (Filesystem) - 5 focused allowed directories
{
  config,
  lib,
  ...
}:
let
  inherit (lib)
    concatStringsSep
    mapAttrs
    filterAttrs
    hasSuffix
    mkEnableOption
    mkIf
    removeSuffix
    toUpper
    ;

  # ═══════════════════════════════════════════════════════════════════════════
  # ACCOUNT REGISTRY SSOT (April 2026)
  # Drives: config dir generation, symlinks, plugin installs, cc shell function
  # ═══════════════════════════════════════════════════════════════════════════

  accountDefs = [
    {
      name = "max-1";
      configDir = null;
      provider = "anthropic";
      description = "Max 20x — primary";
      email = "hank.lee.qed@gmail.com";
      authMethod = "claude.ai";
      model = "opus";
    }
    {
      name = "max-2";
      configDir = ".claude-max-2";
      provider = "anthropic";
      description = "Max 20x — overflow 1";
      email = "hank@told.one";
      authMethod = "claude.ai";
      model = "opus";
    }
    {
      name = "max-3";
      configDir = ".claude-max-3";
      provider = "anthropic";
      description = "Max 20x — overflow 2";
      email = "eng@told.one";
      authMethod = "claude.ai";
      model = "opus";
    }
    {
      name = "max-4";
      configDir = ".claude-max-4";
      provider = "anthropic";
      description = "Max 20x — overflow 3";
      email = ""; # TBD — set after account creation
      authMethod = "claude.ai";
      model = "opus";
    }
    {
      name = "glm";
      configDir = null;
      provider = "zai";
      description = "GLM 5.1 via Z.ai";
      secretId = "told/vendor/zai/api-key";
      email = null;
      authMethod = "api-key";
      model = "glm-5.1";
    }
    {
      name = "openai";
      configDir = null;
      provider = "openrouter";
      description = "GPT-5.3-Codex via OpenRouter";
      secretId = "told/vendor/openrouter/api-key";
      email = null;
      authMethod = "api-key";
      model = "gpt-5.3-codex";
    }
  ];

  # Accounts that need their own config directory (configDir != null)
  alternateConfigDirs = builtins.filter (a: a.configDir != null) accountDefs;

  # Symlink targets shared across all config dirs
  symlinkEntries = [
    {
      suffix = "settings.json";
      source = "${config.home.homeDirectory}/dotfiles/config/quality/generated/claude/settings.json";
    }
    {
      suffix = "commands";
      source = "${config.home.homeDirectory}/dotfiles/config/claude/commands";
    }
    {
      suffix = "skills";
      source = "${config.home.homeDirectory}/dotfiles/config/claude-code/skills";
    }
    {
      suffix = "agents";
      source = "${config.home.homeDirectory}/dotfiles/config/claude-code/agents";
    }
    {
      suffix = "statusline.sh";
      source = "${config.home.homeDirectory}/dotfiles/config/claude/statusline.sh";
    }
  ];

  # Generate home.file attrset for all alternate config dirs
  alternateHomeFiles = builtins.listToAttrs (
    builtins.concatMap (
      acct:
      map (entry: {
        name = "${acct.configDir}/${entry.suffix}";
        value = {
          source = config.lib.file.mkOutOfStoreSymlink entry.source;
        };
      }) symlinkEntries
    ) alternateConfigDirs
  );

  # Bash list of alternate config dir paths for activation hooks
  alternateConfigDirPaths = builtins.concatStringsSep " " (
    map (acct: "\"$HOME/${acct.configDir}\"") alternateConfigDirs
  );

  # Determinate Nix profile paths (in priority order)
  # Uses $USER for portability - resolved at shell runtime, not Nix evaluation
  nixPaths = [
    "/etc/profiles/per-user/$USER/bin"
    "/run/current-system/sw/bin"
    "/nix/var/nix/profiles/default/bin"
    "$HOME/.nix-profile/bin"
    "$HOME/.local/bin" # For uvx (Python MCP servers)
  ];
  pathString = concatStringsSep ":" nixPaths;

  # Generic MCP secrets path (shared across Claude, Gemini, Cursor, etc.)
  mcpSecretsPath = "$HOME/.config/mcp";

  # ═══════════════════════════════════════════════════════════════════════════
  # MCP SERVERS SSOT (March 2026 - MINIMAL)
  # ═══════════════════════════════════════════════════════════════════════════

  mcpServerDefs = {
    ref = {
      # Ref.tools - 60-95% fewer tokens than context7/fetch alternatives
      # Context-aware documentation search with session deduplication
      # https://ref.tools/
      isHttp = true;
      url = "https://api.ref.tools/mcp";
      apiKeyPath = "${mcpSecretsPath}/ref-api-key";
    };
    # Linear: GraphQL API via /linear skill (no MCP server)
  };

  # ═══════════════════════════════════════════════════════════════════════════
  # PLUGINS SSOT (April 2026)
  # ═══════════════════════════════════════════════════════════════════════════

  pluginDefs = {
    default = [ ];
    caveman = [ "caveman" ]; # JuliusBrussee/caveman — terse output, token savings
  };

  enabledPlugins =
    let
      mkPluginEntry = marketplace: plugin: {
        name = "${plugin}@${marketplace}";
        value = true;
      };
      defaultPlugins = map (mkPluginEntry "claude-code-plugins") pluginDefs.default;
      cavemanPlugins = map (mkPluginEntry "caveman") pluginDefs.caveman;
    in
    builtins.listToAttrs (defaultPlugins ++ cavemanPlugins);

  marketplaceDefs = {
    caveman = "JuliusBrussee/caveman"; # Terse output mode — Lite/Full/Ultra intensity
  };

  # JSON for direct injection into .claude.json (no intermediate file needed)
  enabledPluginsJson = builtins.toJSON enabledPlugins;

  # ═══════════════════════════════════════════════════════════════════════════
  # CLAUDE DESKTOP EXTENSIONS SSOT (February 2026)
  # ═══════════════════════════════════════════════════════════════════════════

  # Filesystem extension allowed directories (SOTA: 3-5 focused directories)
  # Avoid large repos with node_modules to prevent 31MB+ directory_tree responses
  filesystemAllowedDirs = [
    "$HOME/src/told" # Primary project
    "$HOME/dotfiles" # System config
    "$HOME/.claude" # Claude state
    "$HOME/Downloads" # File transfers
    "$HOME/Documents" # General docs
    "$HOME/Desktop" # Desktop files
    "$HOME/src/energy" # Energy project
    "$HOME/src/told-vault" # Told vault
    "$HOME/src/haute" # Haute project
    "$HOME/src/korea-real-estate-analytics" # Korea RE analytics
  ];

  filesystemExtensionConfig = builtins.toJSON {
    isEnabled = true;
    userConfig = {
      allowed_directories = filesystemAllowedDirs;
    };
  };

  # ═══════════════════════════════════════════════════════════════════════════
  # Format Generators
  # ═══════════════════════════════════════════════════════════════════════════

  # Generic env sourcing from sops-nix decrypted files
  # Uses semicolon (not &&) for independent sourcing - missing files don't block others
  mkEnvSource =
    def:
    let
      envVars = def.envVars or { };
      sources = lib.mapAttrsToList (
        name: path: "[ -f ${path} ] && export ${name}=$(cat ${path})"
      ) envVars;
    in
    if sources == [ ] then "" else (lib.concatStringsSep "; " sources) + "; ";

  # Filter out HTTP and SSE servers for stdio format generators
  stdioServerDefs = filterAttrs (
    _name: def: !(def.isHttp or false) && !(def.isSse or false)
  ) mcpServerDefs;

  # Desktop-only servers (consumer use, not development)
  # Desktop doesn't support HTTP MCP, so only stdio servers
  # MINIMAL: No desktop servers (January 2026)
  desktopOnlyDefs = { };

  # Claude Desktop format: wrap commands in /bin/sh to inject Nix PATH
  # Electron apps don't inherit shell PATH, so we must inject it
  toDesktopFormat =
    _name: def:
    let
      argsString = if def.args or [ ] == [ ] then "" else " " + (concatStringsSep " " def.args);
      envSource = mkEnvSource def;
    in
    if def.isLocal or false then
      {
        # Local servers (e.g., bun scripts) - wrap with PATH injection
        command = "/bin/sh";
        args = [
          "-c"
          "${envSource}PATH=${pathString}:$PATH exec ${def.command}${argsString}"
        ];
      }
    else if def.isPython or false then
      let
        uvxCmd =
          if def.executable or null != null then
            "uvx --from ${def.package} ${def.executable}"
          else
            "uvx ${def.package}";
      in
      {
        # Python packages via uvx
        command = "/bin/sh";
        args = [
          "-c"
          "${envSource}PATH=${pathString}:$PATH exec ${uvxCmd}${argsString}"
        ];
      }
    else
      {
        # npm packages via npx
        command = "/bin/sh";
        args = [
          "-c"
          "${envSource}PATH=${pathString}:$PATH exec npx -y ${def.package}${argsString}"
        ];
      };

  # Derive placeholder name from secret file path
  # e.g., "~/.config/mcp/exa-api-key" → "__EXA_KEY__"
  # e.g., "~/.config/mcp/github-token" → "__GITHUB_TOKEN__"
  secretPathToPlaceholder =
    path:
    let
      filename = builtins.baseNameOf path;
    in
    if hasSuffix "-api-key" filename then
      let
        prefix = removeSuffix "-api-key" filename;
      in
      "__${toUpper prefix}_KEY__"
    else if hasSuffix "-token" filename then
      let
        prefix = removeSuffix "-token" filename;
      in
      "__${toUpper prefix}_TOKEN__"
    else
      throw "Unknown secret format: ${filename}. Expected *-api-key or *-token";

  # Claude Code CLI format: direct commands (shell has PATH)
  # Uses env field for secrets (cleaner than shell wrapper)
  toCliFormat =
    _name: def:
    let
      hasEnvVars = (def.envVars or { }) != { };
      # Generate env with placeholder values for runtime substitution
      envWithPlaceholders = mapAttrs (_: secretPathToPlaceholder) (def.envVars or { });
    in
    if def.isLocal or false then
      {
        command = def.command;
        args = def.args;
        type = "stdio";
      }
    else if def.isPython or false then
      {
        # Python packages via uvx
        command = "uvx";
        args =
          (
            if def.executable or null != null then
              [
                "--from"
                def.package
                def.executable
              ]
            else
              [ def.package ]
          )
          ++ (def.args or [ ]);
        type = "stdio";
      }
    else if hasEnvVars then
      {
        # npm packages with env vars - use env field with placeholders
        command = "npx";
        args = [
          "-y"
          def.package
        ]
        ++ def.args;
        type = "stdio";
        env = envWithPlaceholders;
      }
    else
      {
        # npm packages via npx
        command = "npx";
        args = [
          "-y"
          def.package
        ]
        ++ def.args;
        type = "stdio";
      };

  # Generate stdio server configs
  desktopStdioServers = mapAttrs toDesktopFormat desktopOnlyDefs; # Only exa for Desktop
  cliStdioServers = mapAttrs toCliFormat stdioServerDefs;

  # HTTP server format for CLI (with placeholder for runtime API key injection)
  # Placeholder format: __SERVERNAME_KEY__ (e.g., __REF_KEY__)
  toCliHttpFormat = name: def: {
    type = "http";
    url = "${def.url}?apiKey=__${toUpper name}_KEY__";
  };

  # SSE server format for CLI (OAuth-based, no API key needed)
  toCliSseFormat = _name: def: {
    type = "sse";
    url = def.url;
  };

  # Filter and generate HTTP server configs (CLI only - Desktop doesn't support HTTP)
  httpServerDefs = filterAttrs (_name: def: def.isHttp or false) mcpServerDefs;
  cliHttpServers = mapAttrs toCliHttpFormat httpServerDefs;

  # Filter and generate SSE server configs (CLI only - Desktop doesn't support SSE)
  sseServerDefs = filterAttrs (_name: def: def.isSse or false) mcpServerDefs;
  cliSseServers = mapAttrs toCliSseFormat sseServerDefs;

  # Combine stdio + HTTP + SSE for full CLI config
  cliAllServers = cliStdioServers // cliHttpServers // cliSseServers;
  cliAllJson = builtins.toJSON cliAllServers;

  # Pre-compute JSON fragments for activation script (strip outer braces)
  desktopStdioJson = builtins.toJSON desktopStdioServers;
  desktopStdioFragment = builtins.substring 1 (
    builtins.stringLength desktopStdioJson - 2
  ) desktopStdioJson;

  # Config JSON for Claude Code CLI (all servers - stdio + HTTP)
  cliConfigJson = builtins.toJSON cliAllServers;

  # ═══════════════════════════════════════════════════════════════════════════
  # GLOBAL JUSTFILE GENERATION (from accountDefs SSOT)
  # Generates ~/.config/just/justfile for `just -g cc` multi-account launcher
  # ═══════════════════════════════════════════════════════════════════════════

  globalJustfileContent =
    let
      padName = name: name + builtins.substring 0 (9 - builtins.stringLength name) "         ";

      # fzf picker entries (one per account, with email if available)
      fzfEntries = map (
        acct:
        let
          emailSuffix = if acct.email != null then " (${acct.email})" else "";
        in
        ''"${padName acct.name}${acct.description}${emailSuffix}"''
      ) accountDefs;

      # Help text lines
      helpEntries = map (acct: ''echo "  ${padName acct.name}${acct.description}"'') accountDefs;

      # Case branches for account dispatch
      mkCaseBranch =
        acct:
        if acct.provider == "anthropic" then
          [
            (
              if acct.configDir != null then
                ''${acct.name}) AI_ACCOUNT="${acct.name}" CLAUDE_CONFIG_DIR="$HOME/${acct.configDir}" claude "$@" ;;''
              else
                ''${acct.name}) unset CLAUDE_CONFIG_DIR; AI_ACCOUNT="${acct.name}" claude "$@" ;;''
            )
          ]
        else if acct.provider == "zai" then
          [
            "${acct.name})"
            "  key=$(aws secretsmanager get-secret-value --secret-id \"${acct.secretId}\" --region us-east-1 --query SecretString --output text 2>/dev/null)"
            "  [[ -z \"$key\" ]] && { echo \"ERROR: Secret ${acct.secretId} missing\" >&2; exit 1; }"
            "  ANTHROPIC_BASE_URL=\"https://api.z.ai/api/anthropic\" \\"
            "  ANTHROPIC_AUTH_TOKEN=\"$key\" \\"
            "  ANTHROPIC_DEFAULT_OPUS_MODEL=\"glm-5.1\" \\"
            "  ANTHROPIC_DEFAULT_SONNET_MODEL=\"glm-5.1\" \\"
            "  ANTHROPIC_DEFAULT_HAIKU_MODEL=\"glm-4.5-air\" \\"
            "  CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 \\"
            "  AI_ACCOUNT=\"${acct.name}\" \\"
            "  claude \"$@\" ;;"
          ]
        else if acct.provider == "openrouter" then
          [
            "${acct.name})"
            "  key=$(aws secretsmanager get-secret-value --secret-id \"${acct.secretId}\" --region us-east-1 --query SecretString --output text 2>/dev/null)"
            "  [[ -z \"$key\" ]] && { echo \"ERROR: Secret ${acct.secretId} missing\" >&2; exit 1; }"
            "  ANTHROPIC_BASE_URL=\"https://openrouter.ai/api\" \\"
            "  ANTHROPIC_AUTH_TOKEN=\"$key\" \\"
            "  ANTHROPIC_MODEL=\"openai/${acct.model}\" \\"
            "  CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 \\"
            "  AI_ACCOUNT=\"${acct.name}\" \\"
            "  claude \"$@\" ;;"
          ]
        else
          [ ];

      caseBranches = builtins.concatLists (map mkCaseBranch accountDefs);

      # Status check entries (reused in both status case and cc-status recipe)
      mkStatusEntry =
        acct:
        let
          emailSuffix = if acct.email != null then " (${acct.email})" else "";
          header = ''echo "=== ${acct.name}${emailSuffix} ==="'';
        in
        if acct.provider == "anthropic" then
          (
            if acct.configDir == null then
              [
                header
                "unset CLAUDE_CONFIG_DIR; claude auth status 2>&1 | jq ."
                ''echo ""''
              ]
            else
              [
                header
                ''CLAUDE_CONFIG_DIR="$HOME/${acct.configDir}" claude auth status 2>&1 | jq .''
                ''echo ""''
              ]
          )
        else
          [
            header
            ''printf '{"provider": "${acct.provider}", "model": "${acct.model}", "authMethod": "${acct.authMethod}", "key": %s}\n' "$(aws secretsmanager get-secret-value --secret-id "${acct.secretId}" --region us-east-1 --query SecretString --output text >/dev/null 2>&1 && echo true || echo false)" | jq .''
            ''echo ""''
          ];

      statusEntries = builtins.concatLists (map mkStatusEntry accountDefs);
    in
    concatStringsSep "\n" (
      [
        "# Claude Code Multi-Account Launcher"
        "# Generated by Nix from accountDefs SSOT. Do not edit manually."
        ""
        ''set shell := ["bash", "-euo", "pipefail", "-c"]''
        ""
        "# Launch Claude Code with account selection"
        "[no-cd]"
        ''cc *args="":''
        "    #!/usr/bin/env bash"
        "    set -euo pipefail"
        "    account=\"\${1:-}\""
        "    shift || true"
        ""
        "    if [[ -z \"$account\" ]]; then"
        "      account=$(printf '%s\\n' \\"
      ]
      ++ map (e: "        ${e} \\") (
        fzfEntries
        ++ [
          ''"---"''
          ''"status   Auth status for all accounts"''
        ]
      )
      ++ [
        "        | fzf --reverse --height=40% --prompt=\"cc > \" \\"
        "        | awk '{print $1}')"
        "      [[ -z \"$account\" || \"$account\" == \"---\" ]] && exit 1"
        "    fi"
        ""
        "    [[ \"$account\" != \"status\" && \"$account\" != \"help\" ]] && echo \"-> cc $account\" >&2"
        ""
        "    case \"$account\" in"
        "      help|-h|--help)"
        "        echo \"Usage: just -g cc [account] [claude args...]\""
        "        echo \"\""
        "        echo \"Accounts:\""
      ]
      ++ map (e: "        ${e}") helpEntries
      ++ [
        "        echo \"\""
        "        echo \"Commands:\""
        "        echo \"  just -g cc             fzf account picker\""
        "        echo \"  just -g cc status      auth status for all accounts\""
        "        echo \"  just -g cc <acct> ...  launch claude with account + passthrough args\""
        "        exit 0 ;;"
      ]
      ++ map (e: "      ${e}") caseBranches
      ++ [
        "      status)"
      ]
      ++ map (e: "        ${e}") statusEntries
      ++ [
        "        ;;"
        "      *) echo \"Unknown: $account. Run 'just -g cc help' for usage.\" >&2; exit 1 ;;"
        "    esac"
        ""
        "# Show auth status for all accounts"
        "[no-cd]"
        "cc-status:"
        "    #!/usr/bin/env bash"
        "    set -euo pipefail"
      ]
      ++ map (e: "    ${e}") statusEntries
      ++ [ "" ]
    );
in
{
  options.modules.home.apps.mcp = {
    enable = mkEnableOption "MCP servers for Claude Desktop, Code CLI, and other agentic IDEs";

    # Expose CLI config for other modules to use
    cliMcpServersJson = lib.mkOption {
      type = lib.types.str;
      default = cliConfigJson;
      readOnly = true;
      description = "Generated MCP servers JSON for Claude Code CLI";
    };
  };

  config = mkIf config.modules.home.apps.mcp.enable (
    lib.mkMerge [
      {
        # ═══════════════════════════════════════════════════════════════════════════
        # Claude Settings & Commands (SSOT - symlinks to Quality System generated files)
        # ═══════════════════════════════════════════════════════════════════════════

        home.file.".claude/settings.json" = {
          source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/dotfiles/config/quality/generated/claude/settings.json";
        };

        home.file.".claude/commands" = {
          source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/dotfiles/config/claude/commands";
        };

        home.file.".claude/skills" = {
          source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/dotfiles/config/claude-code/skills";
        };

        home.file.".claude/agents" = {
          source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/dotfiles/config/claude-code/agents";
        };

        home.file.".claude/statusline.sh" = {
          source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/dotfiles/config/claude/statusline.sh";
        };

        # Global justfile for cc multi-account launcher (just -g cc)
        xdg.configFile."just/justfile".text = globalJustfileContent;

        # ═══════════════════════════════════════════════════════════════════════════
        # MCP Config Generation (Activation-time for HTTP server API key injection)
        # ═══════════════════════════════════════════════════════════════════════════

        # Generate Claude Desktop config (MINIMAL: 0 MCP servers, 1 DXT extension)
        home.activation.generateMcpConfigs = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          DESKTOP_CONFIG="${config.home.homeDirectory}/Library/Application Support/Claude/claude_desktop_config.json"
          mkdir -p "$(dirname "$DESKTOP_CONFIG")"

          cat > "$DESKTOP_CONFIG" << 'DESKTOPEOF'
          {
            "mcpServers": {}
          }
          DESKTOPEOF

          echo "Claude Desktop config generated (0 MCP servers - MINIMAL)"
        '';

        # Generate Claude Desktop Filesystem extension settings (SSOT for allowed_directories)
        home.activation.generateFilesystemExtensionConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          EXT_SETTINGS_DIR="${config.home.homeDirectory}/Library/Application Support/Claude/Claude Extensions Settings"
          EXT_CONFIG="$EXT_SETTINGS_DIR/ant.dir.ant.anthropic.filesystem.json"
          mkdir -p "$EXT_SETTINGS_DIR"

          # Write config with $HOME expanded at activation time
          cat > "$EXT_CONFIG" << EOF
          {
            "isEnabled": true,
            "userConfig": {
              "allowed_directories": [
                "${config.home.homeDirectory}/src/told",
                "${config.home.homeDirectory}/dotfiles",
                "${config.home.homeDirectory}/.claude",
                "${config.home.homeDirectory}/Downloads",
                "${config.home.homeDirectory}/Documents",
                "${config.home.homeDirectory}/Desktop",
                "${config.home.homeDirectory}/src/energy",
                "${config.home.homeDirectory}/src/told-vault",
                "${config.home.homeDirectory}/src/haute",
                "${config.home.homeDirectory}/src/korea-real-estate-analytics"
              ]
            }
          }
          EOF

          echo "Filesystem extension config generated (10 allowed directories from SSOT)"
        '';

        # Generate Claude Code CLI config (~/.claude.json)
        # Uses jq to MERGE mcpServers + enabledPlugins with existing runtime state
        # Runtime state includes: numStartups, oauthAccount, projects, etc. (31+ keys)
        # 1 server (ref), 1 plugin (caveman)
        home.activation.generateClaudeCodeConfig =
          lib.hm.dag.entryAfter [ "writeBoundary" "installPlugins" ]
            ''
              MCP_SECRETS="${config.home.homeDirectory}/.config/mcp"
              CLAUDE_CODE_CONFIG="${config.home.homeDirectory}/.claude.json"

              # Read API key for ref server
              REF_KEY=""
              [ -f "$MCP_SECRETS/ref-api-key" ] && REF_KEY=$(cat "$MCP_SECRETS/ref-api-key")

              # MCP servers JSON from Nix SSOT (with placeholders for secrets)
              MCP_SERVERS='${cliAllJson}'
              ENABLED_PLUGINS='${enabledPluginsJson}'

              # Substitute placeholder with actual secret value
              MCP_SERVERS=$(echo "$MCP_SERVERS" | sed "s/__REF_KEY__/$REF_KEY/g")

              # Merge with existing config (preserve runtime state)
              if [ -f "$CLAUDE_CODE_CONFIG" ]; then
                MERGED=$(jq --argjson servers "$MCP_SERVERS" --argjson plugins "$ENABLED_PLUGINS" \
                  '.mcpServers = $servers | .enabledPlugins = $plugins | del(.defaultModel)' "$CLAUDE_CODE_CONFIG")
                # Only write if content actually changed (prevents Claude Code backup spam)
                CURRENT=$(cat "$CLAUDE_CODE_CONFIG")
                if [ "$MERGED" != "$CURRENT" ]; then
                  echo "$MERGED" > "$CLAUDE_CODE_CONFIG"
                  echo "Claude Code config updated (1 server, 1 plugin)"
                else
                  echo "Claude Code config unchanged, skipping write"
                fi
              else
                echo "{\"mcpServers\": $MCP_SERVERS, \"enabledPlugins\": $ENABLED_PLUGINS}" > "$CLAUDE_CODE_CONFIG"
                echo "Claude Code config created (1 server, 1 plugin)"
              fi

              # Generate .claude.json for alternate config dirs (from accountDefs SSOT)
              # .claude.json is per-config-dir (verified by audit test 3)
              for config_dir in ${alternateConfigDirPaths}; do
                ALT_CONFIG="$config_dir/.claude.json"
                if [ -f "$ALT_CONFIG" ]; then
                  MERGED=$(jq --argjson servers "$MCP_SERVERS" --argjson plugins "$ENABLED_PLUGINS" \
                    '.mcpServers = $servers | .enabledPlugins = $plugins | del(.defaultModel)' "$ALT_CONFIG")
                  CURRENT=$(cat "$ALT_CONFIG")
                  if [ "$MERGED" != "$CURRENT" ]; then
                    echo "$MERGED" > "$ALT_CONFIG"
                    echo "Claude Code config updated in $config_dir (1 server, 1 plugin)"
                  else
                    echo "Claude Code config unchanged in $config_dir, skipping write"
                  fi
                else
                  echo "{\"mcpServers\": $MCP_SERVERS, \"enabledPlugins\": $ENABLED_PLUGINS}" > "$ALT_CONFIG"
                  echo "Claude Code config created in $config_dir (1 server, 1 plugin)"
                fi
              done
            '';

        # Install + enable plugins from marketplace via `claude` CLI (idempotent)
        # Runs BEFORE generateClaudeCodeConfig so the jq merge has final say on enabledPlugins.
        # NOTE: First install requires network (git clone over SSH).
        # If it fails in darwin-rebuild's sandboxed env, run manually:
        #   claude plugin marketplace add JuliusBrussee/caveman --scope user
        #   claude plugin install caveman@caveman --scope user
        home.activation.installPlugins =
          lib.hm.dag.entryAfter
            [
              "writeBoundary"
            ]
            ''
              CLAUDE="/etc/profiles/per-user/${config.home.username}/bin/claude"

              if [ -x "$CLAUDE" ]; then
                # Check if caveman is already installed (skip network-dependent install)
                if $CLAUDE plugin list 2>/dev/null | grep -q "caveman@caveman"; then
                  echo "Caveman plugin already installed"
                else
                  echo "Caveman plugin not found, attempting install..."
                  # Add marketplace (requires git clone — may fail in sandboxed env)
                  if $CLAUDE plugin marketplace add JuliusBrussee/caveman --scope user 2>&1; then
                    $CLAUDE plugin install caveman@caveman --scope user 2>&1 || \
                      echo "WARN: caveman install failed — run manually: claude plugin install caveman@caveman --scope user"
                  else
                    echo "WARN: marketplace add failed (likely SSH/sandbox restriction)"
                    echo "  Run manually: claude plugin marketplace add JuliusBrussee/caveman --scope user"
                  fi
                fi

                # Install caveman in alternate config dirs (from accountDefs SSOT)
                for config_dir in ${alternateConfigDirPaths}; do
                  if CLAUDE_CONFIG_DIR="$config_dir" $CLAUDE plugin list 2>/dev/null | grep -q "caveman@caveman"; then
                    echo "Caveman already installed in $config_dir"
                  else
                    echo "Installing caveman in $config_dir..."
                    CLAUDE_CONFIG_DIR="$config_dir" $CLAUDE plugin marketplace add JuliusBrussee/caveman --scope user 2>&1 || true
                    CLAUDE_CONFIG_DIR="$config_dir" $CLAUDE plugin install caveman@caveman --scope user 2>&1 || \
                      echo "WARN: caveman install failed in $config_dir"
                  fi
                done
              else
                echo "WARN: claude CLI not found, skipping plugin install"
              fi
            '';

        # generateClaudeCodeConfig runs AFTER installPlugins — its jq merge
        # overwrites enabledPlugins with Nix SSOT, ensuring caveman stays enabled
        # even if `claude plugin install` defaults it to disabled.

        # Generate Quality System artifacts (settings.json)
        home.activation.generateQuality = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          QUALITY_DIR="${config.home.homeDirectory}/dotfiles/config/quality"
          BUN="/etc/profiles/per-user/${config.home.username}/bin/bun"

          if [ -f "$QUALITY_DIR/package.json" ]; then
            echo "Generating Intelligence artifacts..."
            cd "$QUALITY_DIR"

            if ! $BUN install --frozen-lockfile; then
              echo "ERROR: bun install failed in $QUALITY_DIR"
              exit 1
            fi

            if ! $BUN run generate; then
              echo "ERROR: Intelligence generation failed in $QUALITY_DIR"
              exit 1
            fi

            echo "Intelligence System artifacts generated successfully"
          fi
        '';

        # Cleanup old plan and todo files (7-day retention)
        # Runs on every `darwin-rebuild switch` or `home-manager switch`
        home.activation.cleanupClaudeEphemeral = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          PLANS_DIR="${config.home.homeDirectory}/.claude/plans"
          TODOS_DIR="${config.home.homeDirectory}/.claude/todos"

          # Delete plan files older than 7 days
          if [ -d "$PLANS_DIR" ]; then
            /usr/bin/find "$PLANS_DIR" -name "*.md" -mtime +7 -type f -delete 2>/dev/null || true
            echo "Claude plans cleanup: removed files older than 7 days"
          fi

          # Delete todo files older than 7 days
          if [ -d "$TODOS_DIR" ]; then
            /usr/bin/find "$TODOS_DIR" -name "*.json" -mtime +7 -type f -delete 2>/dev/null || true
            echo "Claude todos cleanup: removed files older than 7 days"
          fi
        '';

        # ═══════════════════════════════════════════════════════════════════════════
        # LAUNCHD AGENTS (SOTA Log Rotation - February 2026)
        # ═══════════════════════════════════════════════════════════════════════════

        # Claude Desktop log rotation - runs daily at 3am
        # Deletes logs >10MB to prevent disk bloat from large MCP responses
        # SOTA: Keep logs manageable, Filesystem extension can produce 31MB+ responses
        launchd.agents.claude-log-rotation = {
          enable = true;
          config = {
            Label = "com.claude.log-rotation";
            ProgramArguments = [
              "/bin/sh"
              "-c"
              ''
                LOG_DIR="$HOME/Library/Logs/Claude"
                if [ -d "$LOG_DIR" ]; then
                  # Delete logs larger than 10MB
                  /usr/bin/find "$LOG_DIR" -name "*.log" -size +10M -delete 2>/dev/null
                  # Delete rotated logs (numbered backups)
                  /usr/bin/find "$LOG_DIR" -name "*.log.*" -mtime +7 -delete 2>/dev/null
                  echo "$(date): Claude log rotation completed" >> /tmp/claude-log-rotation.log
                fi
              ''
            ];
            StartCalendarInterval = [
              {
                Hour = 3;
                Minute = 0;
              }
            ];
            StandardOutPath = "/tmp/claude-log-rotation.log";
            StandardErrorPath = "/tmp/claude-log-rotation.err";
          };
        };
      }

      # Alternate config dir symlinks (generated from accountDefs SSOT)
      { home.file = alternateHomeFiles; }
    ]
  );
}
