# Codex CLI Multi-Account Launcher (cx)
#
# Mirrors the `cc` picker for Claude Code (modules/home/apps/claude.nix).
# Each account is isolated by setting CODEX_HOME=$HOME/.codex-<name>, which
# overrides the default ~/.codex location for auth.json, config.toml, history,
# and sessions. CODEX_HOME is supported in Codex CLI v0.130+.
#
# Phase A scope (May 2026): two ChatGPT-OAuth Max accounts. No skills, hooks,
# MCP, or AGENTS.md gen yet — those are Phase B (separate Linear ticket).
{
  config,
  lib,
  ...
}:
let
  inherit (lib)
    concatStringsSep
    mkEnableOption
    mkIf
    ;

  # ═══════════════════════════════════════════════════════════════════════════
  # CODEX ACCOUNT REGISTRY SSOT
  # Drives: cx fzf picker entries, dispatch case, cx-status recipe.
  # ═══════════════════════════════════════════════════════════════════════════

  codexAccountDefs = [
    {
      name = "codex-max-1";
      codexHome = ".codex-max-1";
      description = "Codex Max — primary";
      email = "hank.lee.qed@gmail.com";
      authMethod = "chatgpt-oauth";
    }
    # Add additional accounts here when needed (e.g., codex-max-2 with hank@told.one).
  ];

  # ═══════════════════════════════════════════════════════════════════════════
  # `cx` RECIPE GENERATION (mirrors claude.nix:411–576)
  # ═══════════════════════════════════════════════════════════════════════════

  cxRecipeContent =
    let
      # Pad to 13 chars so "codex-max-N" + description columns line up
      padName = name: name + builtins.substring 0 (13 - builtins.stringLength name) "             ";

      fzfEntries = map (
        acct:
        let
          emailSuffix = if acct.email != null then " (${acct.email})" else "";
        in
        ''"${padName acct.name}${acct.description}${emailSuffix}"''
      ) codexAccountDefs;

      helpEntries = map (acct: ''echo "  ${padName acct.name}${acct.description}"'') codexAccountDefs;

      mkCaseBranch =
        acct:
        ''${acct.name}) AI_ACCOUNT="${acct.name}" CODEX_HOME="$HOME/${acct.codexHome}" codex "$@" ;;'';

      caseBranches = map mkCaseBranch codexAccountDefs;

      mkStatusEntry =
        acct:
        let
          emailSuffix = if acct.email != null then " (${acct.email})" else "";
          header = ''echo "=== ${acct.name}${emailSuffix} ==="'';
        in
        [
          header
          ''CODEX_HOME="$HOME/${acct.codexHome}" codex login status 2>&1 || true''
          ''echo ""''
        ];

      statusEntries = builtins.concatLists (map mkStatusEntry codexAccountDefs);
    in
    concatStringsSep "\n" (
      [
        "# ─── Codex CLI Multi-Account Launcher (cx) ──────────────────────────────"
        "# Generated by Nix from codexAccountDefs SSOT in modules/home/apps/codex.nix."
        ""
        "# Launch Codex CLI with account selection"
        "[no-cd]"
        ''cx *args="":''
        "    #!/usr/bin/env bash"
        "    set -euo pipefail"
        "    # just doesn't pass variadic recipe args to shebang scripts as $1, $2."
        "    # Use {{args}} interpolation to populate bash positional args."
        "    set -- {{args}}"
        "    account=\"\${1:-}\""
        "    shift || true"
        ""
        "    if [[ -z \"$account\" ]]; then"
        "      account=$(printf '%s\\n' \\"
      ]
      ++ map (e: "        ${e} \\") (
        fzfEntries
        ++ [
          ''"---"''
          ''"status   Auth status for all accounts"''
        ]
      )
      ++ [
        "        | fzf --reverse --height=40% --prompt=\"cx > \" \\"
        "        | awk '{print $1}')"
        "      [[ -z \"$account\" || \"$account\" == \"---\" ]] && exit 1"
        "    fi"
        ""
        "    [[ \"$account\" != \"status\" && \"$account\" != \"help\" ]] && echo \"-> cx $account\" >&2"
        ""
        "    case \"$account\" in"
        "      help|-h|--help)"
        "        echo \"Usage: just -g cx [account] [codex args...]\""
        "        echo \"\""
        "        echo \"Accounts:\""
      ]
      ++ map (e: "        ${e}") helpEntries
      ++ [
        "        echo \"\""
        "        echo \"Commands:\""
        "        echo \"  just -g cx             fzf account picker\""
        "        echo \"  just -g cx status      auth status for all accounts\""
        "        echo \"  just -g cx <acct> ...  launch codex with account + passthrough args\""
        "        exit 0 ;;"
      ]
      ++ map (e: "      ${e}") caseBranches
      ++ [
        "      status)"
      ]
      ++ map (e: "        ${e}") statusEntries
      ++ [
        "        ;;"
        "      *) echo \"Unknown: $account. Run 'just -g cx help' for usage.\" >&2; exit 1 ;;"
        "    esac"
        ""
        "# Show auth status for all Codex accounts"
        "[no-cd]"
        "cx-status:"
        "    #!/usr/bin/env bash"
        "    set -euo pipefail"
      ]
      ++ map (e: "    ${e}") statusEntries
      ++ [ "" ]
    );
in
{
  options.modules.home.apps.codex = {
    enable = mkEnableOption "Codex CLI multi-account launcher (cx) with CODEX_HOME-based isolation";

    cxJustRecipes = lib.mkOption {
      type = lib.types.str;
      default = cxRecipeContent;
      readOnly = true;
      description = "Generated `cx` recipes (without shared header) for the global justfile";
    };
  };

  config = mkIf config.modules.home.apps.codex.enable {
    # No file writes here — agents-launcher.nix consumes cxJustRecipes and
    # writes the combined ~/.config/just/justfile.
    #
    # The Codex CLI binary itself is installed via the `codex` Homebrew cask
    # (see modules/homebrew.nix). Account dirs (~/.codex-max-N) are created
    # on first OAuth login when CODEX_HOME points at them.
  };
}
