# Kanata keyboard remapper - user config
# Cross-platform software keyboard remapper with QMK-like features
# Requires Karabiner driver on macOS: brew install karabiner-elements
#
# The daemon runs via nix-darwin (modules/darwin/kanata.nix)
# This module generates the config and provides a helper script
#
# Key mappings:
#   Space: Space (tap) | Symbols layer (hold)
#   Right Alt: Navigation layer (hold)
{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib) mkEnableOption mkIf;
  cfg = config.modules.home.apps.kanata;

  # Timing configuration (easily adjustable)
  tapTime = 200;
  holdTime = 200;

  # Generated Kanata config - minimal, no home-row mods
  kanataConfig = ''
    ;; Kanata Configuration - Generated by Nix
    ;;
    ;; Key mappings:
    ;;   Space: Space (tap) | Symbols layer (hold)
    ;;   Right Alt: Navigation layer (hold)

    (defcfg
      process-unmapped-keys yes
      concurrent-tap-hold yes
      log-layer-changes no
    )

    ;; ============================================================================
    ;; Source Layout (physical keys we're remapping)
    ;; ============================================================================
    (defsrc
      esc  1    2    3    4    5    6    7    8    9    0    -    =    bspc
      tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
      caps a    s    d    f    g    h    j    k    l    ;    '    ret
      lsft z    x    c    v    b    n    m    ,    .    /    rsft
      fn   lctl lalt lmet           spc            rmet ralt rctl
    )

    ;; ============================================================================
    ;; Variables
    ;; ============================================================================
    (defvar
      tap-time ${toString tapTime}
      hold-time ${toString holdTime}
    )

    ;; ============================================================================
    ;; Aliases (key behaviors)
    ;; ============================================================================
    (defalias
      ;; Layer toggles
      sym (layer-toggle symbols)
      nav (layer-toggle navigation)

      ;; Space: Normal space, or hold for symbols layer
      spc (tap-hold $tap-time $hold-time spc @sym)
    )

    ;; ============================================================================
    ;; Layers
    ;; ============================================================================

    ;; Base layer - minimal config, no home-row mods
    (deflayer base
      esc  1    2    3    4    5    6    7    8    9    0    -    =    bspc
      tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
      caps a    s    d    f    g    h    j    k    l    ;    '    ret
      lsft z    x    c    v    b    n    m    ,    .    /    rsft
      fn   lctl lalt lmet           @spc           rmet @nav rctl
    )

    ;; Symbols layer (activated by holding space)
    ;; Number row: shifted symbols (!@#$%^&*())
    ;; Home row: numbers 1-0
    ;; Provides quick access to symbols and numbers without leaving home row
    (deflayer symbols
      _    S-1  S-2  S-3  S-4  S-5  S-6  S-7  S-8  S-9  S-0  S--  S-=  _
      _    S-1  S-2  S-3  S-4  S-5  S-6  S-7  S-8  S-9  S-0  S-[  S-]  S-\
      _    1    2    3    4    5    6    7    8    9    0    `    _
      _    S-`  `    _    _    _    -    =    S-,  S-.  S-/  _
      _    _    _    _              _              _    _    _
    )

    ;; Navigation layer (activated by holding right alt)
    ;; Vim-style arrows on home row: h=left, j=down, k=up, l=right
    ;; Also: y=home, u=pgup, i=pgdn, o=end
    (deflayer navigation
      _    _    _    _    _    _    _    _    _    _    _    _    _    _
      _    _    _    _    _    _    home pgup pgdn end  _    _    _    _
      _    _    _    _    _    _    left down up   rght _    _    _
      _    _    _    _    _    _    _    _    _    _    _    _
      _    _    _    _              _              _    _    _
    )
  '';
in
{
  options.modules.home.apps.kanata = {
    enable = mkEnableOption "Kanata keyboard remapper config";
  };

  config = mkIf cfg.enable {
    # Install kanata binary (for manual testing)
    home.packages = [ pkgs.kanata ];

    # Generate config from Nix (not sourced from external file)
    xdg.configFile."kanata/kanata.kbd".text = kanataConfig;

    # Create a helper script for manual kanata execution
    home.file.".local/bin/kanata-start" = {
      executable = true;
      text = ''
        #!/bin/bash
        # Start Kanata keyboard remapper manually
        # Note: The daemon runs via launchd (see modules/darwin/kanata.nix)
        exec sudo ${pkgs.kanata}/bin/kanata --cfg "$HOME/.config/kanata/kanata.kbd"
      '';
    };
  };
}
