# Generic MCP Server Single Source of Truth
# Generates configs for: Claude Desktop AND Claude Code CLI (fully declarative)
#
# ARCHITECTURE (December 2025 - DECLARATIVE):
# - Claude Desktop: Reads ~/Library/Application Support/Claude/claude_desktop_config.json
#   → Generated by Nix activation hook (Electron app needs PATH injection)
# - Claude Code CLI: Reads ~/.claude.json
#   → Generated by Nix activation hook (merges with runtime state via jq)
#
# Both configs are derived from mcpServerDefs (SSOT).
# No manual scripts required after darwin-rebuild.
#
# Token Optimization (December 2025):
# - Reduced from 16 to 6 MCP servers (~75% token reduction)
# - SOTA servers: Ref.tools (60-95% fewer tokens), Exa AI (code search)
# - Removed redundant servers that duplicate native Claude Code capabilities
{
  config,
  lib,
  ...
}:
let
  inherit (lib)
    concatStringsSep
    mapAttrs
    filterAttrs
    hasSuffix
    mkEnableOption
    mkIf
    removeSuffix
    toUpper
    ;

  # Determinate Nix profile paths (in priority order)
  nixPaths = [
    "/etc/profiles/per-user/hank/bin"
    "/run/current-system/sw/bin"
    "/nix/var/nix/profiles/default/bin"
    "$HOME/.nix-profile/bin"
    "$HOME/.local/bin" # For uvx (Python MCP servers)
  ];
  pathString = concatStringsSep ":" nixPaths;

  # Generic MCP secrets path (shared across Claude, Gemini, Cursor, etc.)
  mcpSecretsPath = "$HOME/.config/mcp";

  # ═══════════════════════════════════════════════════════════════════════════
  # SINGLE SOURCE OF TRUTH: MCP Server Definitions (Optimized December 2025)
  # ═══════════════════════════════════════════════════════════════════════════
  # Target: <25k tokens (down from ~116k)
  # Strategy: SOTA search/docs (Ref, Exa) + unique capabilities only
  mcpServerDefs = {
    # ═══════════════════════════════════════════════════════════════════════════
    # DOCUMENTATION & SEARCH (State-of-the-Art - December 2025)
    # ═══════════════════════════════════════════════════════════════════════════

    ref = {
      # Ref.tools - 60-95% fewer tokens than context7/fetch alternatives
      # Context-aware documentation search with session deduplication
      # https://ref.tools/
      isHttp = true;
      url = "https://api.ref.tools/mcp";
      # API key will be appended at activation time from sops-nix
      apiKeyPath = "${mcpSecretsPath}/ref-api-key";
    };

    exa = {
      # Exa AI - Code context search across billions of repos
      # Tools: get_code_context_exa, web_search_exa
      # https://exa.ai/
      package = "exa-mcp-server";
      args = [ ];
      envVars = {
        EXA_API_KEY = "${mcpSecretsPath}/exa-api-key";
      };
    };

    # ═══════════════════════════════════════════════════════════════════════════
    # UNIQUE CAPABILITIES (No native Claude Code equivalent)
    # ═══════════════════════════════════════════════════════════════════════════

    github = {
      # GitHub API: repos, issues, PRs, code search
      # Token sourced from sops-nix secret file
      package = "@modelcontextprotocol/server-github";
      args = [ ];
      envVars = {
        GITHUB_PERSONAL_ACCESS_TOKEN = "${mcpSecretsPath}/github-token";
      };
    };

    playwright = {
      # Browser automation for testing and web interactions
      package = "@playwright/mcp";
      args = [ ];
    };

    ast-grep = {
      # AST-based structural code search across 20+ languages
      package = "@notprolands/ast-grep-mcp";
      args = [ ];
    };

    repomix = {
      # Codebase packaging for AI analysis
      package = "repomix";
      args = [ "--mcp" ];
    };
  };

  # ═══════════════════════════════════════════════════════════════════════════
  # Format Generators
  # ═══════════════════════════════════════════════════════════════════════════

  # Generic env sourcing from sops-nix decrypted files
  # Uses semicolon (not &&) for independent sourcing - missing files don't block others
  mkEnvSource =
    def:
    let
      envVars = def.envVars or { };
      sources = lib.mapAttrsToList (
        name: path: "[ -f ${path} ] && export ${name}=$(cat ${path})"
      ) envVars;
    in
    if sources == [ ] then "" else (lib.concatStringsSep "; " sources) + "; ";

  # Filter out HTTP and SSE servers for stdio format generators
  stdioServerDefs = filterAttrs (
    _name: def: !(def.isHttp or false) && !(def.isSse or false)
  ) mcpServerDefs;

  # Desktop-only servers (consumer use, not development)
  # Desktop doesn't support HTTP MCP, so only stdio servers
  desktopOnlyDefs = {
    exa = mcpServerDefs.exa; # Web/code search for casual use
  };

  # Claude Desktop format: wrap commands in /bin/sh to inject Nix PATH
  # Electron apps don't inherit shell PATH, so we must inject it
  toDesktopFormat =
    _name: def:
    let
      argsString = if def.args or [ ] == [ ] then "" else " " + (concatStringsSep " " def.args);
      envSource = mkEnvSource def;
    in
    if def.isLocal or false then
      {
        # Local servers (e.g., bun scripts) - wrap with PATH injection
        command = "/bin/sh";
        args = [
          "-c"
          "${envSource}PATH=${pathString}:$PATH exec ${def.command}${argsString}"
        ];
      }
    else if def.isPython or false then
      {
        # Python packages via uvx
        command = "/bin/sh";
        args = [
          "-c"
          "${envSource}PATH=${pathString}:$PATH exec uvx ${def.package}${argsString}"
        ];
      }
    else
      {
        # npm packages via npx
        command = "/bin/sh";
        args = [
          "-c"
          "${envSource}PATH=${pathString}:$PATH exec npx -y ${def.package}${argsString}"
        ];
      };

  # Derive placeholder name from secret file path
  # e.g., "~/.config/mcp/exa-api-key" → "__EXA_KEY__"
  # e.g., "~/.config/mcp/github-token" → "__GITHUB_TOKEN__"
  secretPathToPlaceholder =
    path:
    let
      filename = builtins.baseNameOf path;
    in
    if hasSuffix "-api-key" filename then
      let
        prefix = removeSuffix "-api-key" filename;
      in
      "__${toUpper prefix}_KEY__"
    else if hasSuffix "-token" filename then
      let
        prefix = removeSuffix "-token" filename;
      in
      "__${toUpper prefix}_TOKEN__"
    else
      throw "Unknown secret format: ${filename}. Expected *-api-key or *-token";

  # Claude Code CLI format: direct commands (shell has PATH)
  # Uses env field for secrets (cleaner than shell wrapper)
  toCliFormat =
    _name: def:
    let
      hasEnvVars = (def.envVars or { }) != { };
      # Generate env with placeholder values for runtime substitution
      envWithPlaceholders = mapAttrs (_: secretPathToPlaceholder) (def.envVars or { });
    in
    if def.isLocal or false then
      {
        command = def.command;
        args = def.args;
        type = "stdio";
      }
    else if def.isPython or false then
      {
        # Python packages via uvx
        command = "uvx";
        args = [ def.package ] ++ def.args;
        type = "stdio";
      }
    else if hasEnvVars then
      {
        # npm packages with env vars - use env field with placeholders
        command = "npx";
        args = [
          "-y"
          def.package
        ]
        ++ def.args;
        type = "stdio";
        env = envWithPlaceholders;
      }
    else
      {
        # npm packages via npx
        command = "npx";
        args = [
          "-y"
          def.package
        ]
        ++ def.args;
        type = "stdio";
      };

  # Generate stdio server configs
  desktopStdioServers = mapAttrs toDesktopFormat desktopOnlyDefs; # Only exa for Desktop
  cliStdioServers = mapAttrs toCliFormat stdioServerDefs;

  # HTTP server format for CLI (with placeholder for runtime API key injection)
  # Placeholder format: __SERVERNAME_KEY__ (e.g., __REF_KEY__)
  toCliHttpFormat = name: def: {
    type = "http";
    url = "${def.url}?apiKey=__${toUpper name}_KEY__";
  };

  # SSE server format for CLI (OAuth-based, no API key needed)
  toCliSseFormat = _name: def: {
    type = "sse";
    url = def.url;
  };

  # Filter and generate HTTP server configs (CLI only - Desktop doesn't support HTTP)
  httpServerDefs = filterAttrs (_name: def: def.isHttp or false) mcpServerDefs;
  cliHttpServers = mapAttrs toCliHttpFormat httpServerDefs;

  # Filter and generate SSE server configs (CLI only - Desktop doesn't support SSE)
  sseServerDefs = filterAttrs (_name: def: def.isSse or false) mcpServerDefs;
  cliSseServers = mapAttrs toCliSseFormat sseServerDefs;

  # Combine stdio + HTTP + SSE for full CLI config
  cliAllServers = cliStdioServers // cliHttpServers // cliSseServers;
  cliAllJson = builtins.toJSON cliAllServers;

  # Pre-compute JSON fragments for activation script (strip outer braces)
  desktopStdioJson = builtins.toJSON desktopStdioServers;
  desktopStdioFragment = builtins.substring 1 (
    builtins.stringLength desktopStdioJson - 2
  ) desktopStdioJson;

  # Config JSON for Claude Code CLI (all servers - stdio + HTTP)
  cliConfigJson = builtins.toJSON cliAllServers;
in
{
  options.modules.home.apps.mcp = {
    enable = mkEnableOption "MCP servers for Claude Desktop, Code CLI, and other agentic IDEs";

    # Expose CLI config for other modules to use
    cliMcpServersJson = lib.mkOption {
      type = lib.types.str;
      default = cliConfigJson;
      readOnly = true;
      description = "Generated MCP servers JSON for Claude Code CLI";
    };
  };

  config = mkIf config.modules.home.apps.mcp.enable {
    # ═══════════════════════════════════════════════════════════════════════════
    # Claude Settings & Skills (SSOT - symlinks to Quality System generated files)
    # ═══════════════════════════════════════════════════════════════════════════

    home.file.".claude/settings.json" = {
      source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/dotfiles/config/quality/generated/claude/settings.json";
    };

    home.file.".claude/skills" = {
      source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/dotfiles/config/quality/generated/claude/skills";
    };

    home.file.".claude/agents" = {
      source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/dotfiles/config/quality/generated/claude/personas";
    };

    # ═══════════════════════════════════════════════════════════════════════════
    # MCP Config Generation (Activation-time for HTTP server API key injection)
    # ═══════════════════════════════════════════════════════════════════════════

    # Generate Claude Desktop config (stdio servers only - Desktop doesn't support HTTP MCP)
    home.activation.generateMcpConfigs = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
            DESKTOP_CONFIG="${config.home.homeDirectory}/Library/Application Support/Claude/claude_desktop_config.json"
            mkdir -p "$(dirname "$DESKTOP_CONFIG")"

            cat > "$DESKTOP_CONFIG" << DESKTOPEOF
      {
        "mcpServers": {
          ${desktopStdioFragment}
        }
      }
      DESKTOPEOF

            echo "Claude Desktop config generated (1 stdio server: exa only)"
    '';

    # Generate Claude Code CLI config (~/.claude.json)
    # Uses jq to MERGE mcpServers key with existing runtime state
    # Runtime state includes: numStartups, oauthAccount, projects, etc. (31+ keys)
    # Server definitions derived from mcpServerDefs (SSOT)
    home.activation.generateClaudeCodeConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      MCP_SECRETS="${config.home.homeDirectory}/.config/mcp"
      CLAUDE_CODE_CONFIG="${config.home.homeDirectory}/.claude.json"

      # Read API keys for servers requiring authentication
      REF_KEY=""
      [ -f "$MCP_SECRETS/ref-api-key" ] && REF_KEY=$(cat "$MCP_SECRETS/ref-api-key")

      EXA_KEY=""
      [ -f "$MCP_SECRETS/exa-api-key" ] && EXA_KEY=$(cat "$MCP_SECRETS/exa-api-key")

      GITHUB_TOKEN=""
      [ -f "$MCP_SECRETS/github-token" ] && GITHUB_TOKEN=$(cat "$MCP_SECRETS/github-token")

      # MCP servers JSON from Nix SSOT (with placeholders for secrets)
      MCP_SERVERS='${cliAllJson}'

      # Substitute placeholders with actual secret values
      MCP_SERVERS=$(echo "$MCP_SERVERS" | sed "s/__REF_KEY__/$REF_KEY/g")
      MCP_SERVERS=$(echo "$MCP_SERVERS" | sed "s/__EXA_KEY__/$EXA_KEY/g")
      MCP_SERVERS=$(echo "$MCP_SERVERS" | sed "s/__GITHUB_TOKEN__/$GITHUB_TOKEN/g")

      # Merge with existing config (preserve runtime state)
      if [ -f "$CLAUDE_CODE_CONFIG" ]; then
        MERGED=$(jq --argjson servers "$MCP_SERVERS" '.mcpServers = $servers' "$CLAUDE_CODE_CONFIG")
        echo "$MERGED" > "$CLAUDE_CODE_CONFIG"
        echo "Claude Code config updated (6 servers from SSOT)"
      else
        echo "{\"mcpServers\": $MCP_SERVERS}" > "$CLAUDE_CODE_CONFIG"
        echo "Claude Code config created (6 servers from SSOT)"
      fi
    '';

    # Generate Quality System artifacts (skills, personas, rules, settings)
    # Runs after writeBoundary to ensure all files are in place
    home.activation.generateQuality = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      QUALITY_DIR="${config.home.homeDirectory}/dotfiles/config/quality"
      BUN="/etc/profiles/per-user/${config.home.username}/bin/bun"

      if [ -f "$QUALITY_DIR/package.json" ]; then
        echo "Generating Intelligence artifacts..."
        cd "$QUALITY_DIR"

        if ! $BUN install --frozen-lockfile; then
          echo "ERROR: bun install failed in $QUALITY_DIR"
          exit 1
        fi

        if ! $BUN run generate; then
          echo "ERROR: Intelligence generation failed in $QUALITY_DIR"
          exit 1
        fi

        echo "Intelligence System artifacts generated successfully"
      fi
    '';
  };
}
