/**
 * Gemini Generator Adapter
 *
 * Generates single-file GEMINI.md system prompt for Antigravity.
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import { Effect } from 'effect'
import type { PersonaDefinition, SkillDefinition } from '../../schemas'

export const generateGeminiConfig = (
  skills: readonly SkillDefinition[],
  personas: readonly PersonaDefinition[],
  outDir: string,
) =>
  Effect.gen(function* () {
    yield* Effect.tryPromise(() => fs.mkdir(outDir, { recursive: true }))

    // Header
    let content = `# System Instructions (Gemini/Antigravity)

> Generated by Brain System. Do not edit manually.

`

    // Personas Section
    content += `## Personas\n\n`
    for (const persona of personas) {
      content += `### ${persona.name}\n\n`
      content += `${persona.description}\n\n`
      content += `${persona.systemPrompt}\n\n`
      content += `---\n\n`
    }

    // Skills Section
    content += `## Skills\n\n`
    for (const skill of skills) {
      content += `### ${skill.frontmatter.name}\n\n`
      content += `> ${skill.frontmatter.description}\n\n`
      for (const section of skill.sections) {
        content += `#### ${section.heading}\n\n${section.content}\n\n`
      }
      content += `---\n\n`
    }

    const filePath = path.join(outDir, 'GEMINI.md')
    yield* Effect.tryPromise(() => fs.writeFile(filePath, content))
    yield* Effect.log(`Generated Gemini Config: ${filePath}`)
  })
