/**
 * Nix Config Schema - Effect Schema for Nix-generated JSON
 *
 * TypeScript consumes this JSON generated by Nix activation hooks.
 * SSOT: modules/home/apps/claude.nix → generated/nix-config.json → TypeScript
 */

import { Schema } from 'effect'

// =============================================================================
// Marketplace Source Schema (for extraKnownMarketplaces)
// =============================================================================

const MarketplaceSourceSchema = Schema.Struct({
  source: Schema.Literal('github'),
  repo: Schema.String,
})

const MarketplaceDefSchema = Schema.Struct({
  source: MarketplaceSourceSchema,
})

// =============================================================================
// Nix Config Schema
// =============================================================================

export const NixConfigSchema = Schema.Struct({
  enabledPlugins: Schema.Record({ key: Schema.String, value: Schema.Boolean }),
  extraKnownMarketplaces: Schema.Record({ key: Schema.String, value: MarketplaceDefSchema }),
})

// Types derived FROM schema (Effect Schema as SSOT)
export type NixConfig = typeof NixConfigSchema.Type

// Decoder (Effect-native, never throws)
export const decodeNixConfig = Schema.decodeUnknown(NixConfigSchema)
