# sops-nix configuration
# Age public key for encrypting secrets
keys:
  - &hank age1vvyhapanqw8q3rjq5a0p9z66rh5c342satmrn4g4hs9lqcqhhglq9nkzr6

creation_rules:
  # All secrets in the secrets directory
  - path_regex: .*secrets.*\.yaml$
    key_groups:
      - age:
          - *hank
  # Catch-all for any yaml
  - path_regex: .*\.yaml$
    key_groups:
      - age:
          - *hank
