##################################
# Taps
##################################
tap "coder/coder"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "olets/tap"
tap "rfidresearchgroup/proxmark3"
tap "sachaos/todoist"
tap "stripe/stripe-cli"
tap "temporalio/brew"
tap "typesense/tap"
tap "waydabber/betterdisplay"
tap "xo/xo"
tap "yakitrak/yakitrak"

##################################
# Formulae
##################################
brew "rfidresearchgroup/proxmark3/arm-none-eabi-gcc"
brew "rfidresearchgroup/proxmark3/proxmark3"
brew "act"
brew "shellcheck"
brew "actionlint"
brew "aider"
brew "angle-grinder"
brew "ast-grep"
brew "atuin", restart_service: :changed
brew "localstack"
brew "awscli-local"
brew "bat"
brew "biome"
brew "bitwarden-cli"
brew "bottom"
brew "broot"
brew "cheat"
brew "chrome-cli"
brew "cloudflare-wrangler2"
brew "curl"
brew "curlie"
brew "cutter"
brew "wget"
brew "dasht"
brew "datasette"
brew "direnv"
brew "duf"
brew "dust"
brew "esbuild"
brew "eslint"
brew "exiftool"
brew "eza"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "fx"
brew "fzf"
brew "gdrive"
brew "gdrive-downloader"
brew "gh"
brew "ghi"
brew "git"
brew "git-delta"
brew "glances"
brew "glow"
brew "gping"
brew "grex"
brew "gron"
brew "helix"
brew "hexyl"
brew "htop"
brew "http-prompt"
brew "httrack"
brew "hurl"
brew "hyperfine"
brew "imagemagick"
brew "jd"
brew "jq"
brew "just"
brew "k9s"
brew "kanata"
brew "lazygit"
brew "lnav"
brew "lsd"
brew "lua-language-server"
brew "luarocks"
brew "mas"
brew "mcfly"
brew "miller"
brew "minio"
brew "nasm"
brew "neovim"
brew "netcat"
brew "nextdns"
brew "nmap"
brew "nnn"
brew "odin"
brew "onefetch"
brew "pandoc"
brew "parallel"
brew "pinentry-mac"
brew "pkgconf"
brew "poppler"
brew "posting"
brew "prettier"
brew "procs"
brew "prometheus"
brew "pyenv"
brew "rclone"
brew "ripgrep"
brew "rollup"
brew "ruff"
brew "rust"
brew "rust-analyzer"
brew "rustscan"
brew "rustup"
brew "scrapy"
brew "sd"
brew "sevenzip"
brew "skaffold"
brew "sonic"
brew "speedtest-cli"
brew "speexdsp"
brew "sq"
brew "starship"
brew "temporal"
brew "tldr"
brew "traefik"
brew "tree"
brew "trippy"
brew "uv"
brew "vite"
brew "volta"
brew "weasyprint"
brew "xclip"
brew "xcodes"
brew "xh"
brew "yazi"
brew "yq"
brew "yt-dlp"
brew "zellij"
brew "zoxide"
brew "zsh-autopair"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "coder/coder/coder"
brew "koekeishiya/formulae/skhd"
brew "olets/tap/zsh-abbr"
brew "olets/tap/zsh-autosuggestions-abbreviations-strategy"
brew "sachaos/todoist/todoist"
brew "stripe/stripe-cli/stripe"
brew "temporalio/brew/tcld"
brew "yakitrak/yakitrak/obsidian-cli"

# Newly added formulae that were slated for uninstall:
brew "diff-so-fancy"
brew "neofetch"
brew "screenresolution"
brew "syncthing"
brew "tmux"
brew "utf8proc"
brew "util-linux"
brew "yakitrak/yakitrak/obs"

##################################
# Casks
##################################
# Combined and alphabetically sorted old + newly added casks

cask "slack"
cask "a-better-finder-rename"
cask "affine"
cask "aide-app"
cask "amazon-chime"
cask "anki"
cask "apidog"
cask "arc"
cask "arq"
cask "asana"
cask "bartender"
cask "betterdisplay"
cask "boltai"
cask "brave-browser"
cask "bunch"
cask "buttercup"
cask "canva"
cask "carbon-copy-cloner"
cask "cardhop"
cask "charmstone"
cask "chatgpt"
cask "claude"
cask "cleanshot"
cask "copilot"
cask "cork"
cask "cursor"
cask "dash"
cask "devonthink"
cask "devutils"
cask "espanso"
cask "fantastical"
cask "figma"
cask "firefox"
cask "font-jetbrains-mono-nerd-font"
cask "font-mononoki-nerd-font"
cask "font-noto-nerd-font"
cask "font-symbols-only-nerd-font"
cask "font-ubuntu-nerd-font"
cask "follow"
cask "ghidra"
cask "ghostty"
cask "gitkraken"
cask "google-chrome"
cask "google-drive"
cask "hammerspoon"
cask "hazel"
cask "homerow"
cask "hopper-disassembler"
cask "hoppscotch"
cask "httpie"
cask "istat-menus"
cask "itsycal"
cask "jump"
cask "jump-desktop-connect"
cask "kaleidoscope"
cask "karabiner-elements"
cask "keka"
cask "kekaexternalhelper"
cask "keycastr"
cask "keymapp"
cask "lm-studio"
cask "miro"
cask "motrix"
cask "mullvadvpn"
cask "neo4j"
cask "obsidian"
cask "ollama"
cask "orbstack"
cask "osquery"
cask "parallels"
cask "parsec"
cask "pdf-expert"
cask "proton-drive"
cask "proton-mail"
cask "proton-pass"
cask "protonvpn"
cask "proxyman"
cask "qflipper"
cask "qutebrowser"
cask "raycast"
cask "rize"
cask "royal-tsx"
cask "sensei"
cask "setapp"
cask "sf-symbols"
cask "signal"
cask "soulver"
cask "soundsource"
cask "spotify"
cask "stack"
cask "superhuman"
cask "swish"
cask "synologyassistant"
cask "tableplus"
cask "tailscale"
# cask "termius"
cask "textexpander"
cask "timelane"
cask "tower"
cask "typora"
cask "virtualbuddy"
cask "visual-studio-code"
cask "wireshark"
cask "windsurf"
cask "yubico-yubikey-manager"
cask "zen-browser"
cask "zed"
cask "zoom"

##################################
# Mac App Store
##################################
mas "Amphetamine", id: 937984704
mas "Bear", id: 1091189122
# mas "Bitwarden", id: 1352778147
mas "Cleaner One Pro", id: 1133028347
mas "CleanMyMac", id: 1339170533
mas "DaisyDisk", id: 411643860
mas "Day One", id: 1055511498
mas "Drafts", id: 1435957248
mas "Dropover", id: 1355679052
mas "ExcalidrawZ", id: 6636493997
mas "Fantastical", id: 975937182
mas "Flighty", id: 1358823008
mas "Flow", id: 1423210932
mas "Focus", id: 777233759
mas "Journey", id: 1662059644
mas "KakaoTalk", id: 869223134
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "LanScan", id: 472226235
mas "NextDNS", id: 1464122853
mas "Numbers", id: 409203825
mas "Omnivore", id: 1564031042
mas "One Thing", id: 1604176982
mas "Pages", id: 409201541
mas "Pandan", id: 1569600264
mas "Parcel", id: 639968404
mas "Pixea", id: 1507782672
mas "SnippetsLab", id: 1006087419
mas "Snippety", id: 1530751461
mas "Snippit", id: 1465481124
mas "Termius", id: 1176074088
mas "Todoist", id: 585829637
mas "Toggl Track", id: 1291898086
mas "Tripsy", id: 1429967544
mas "Yoink", id: 457622435
mas "Yubico Authenticator", id: 1497506650

##################################
# VSCode Extensions
##################################
vscode "aaron-bond.better-comments"
vscode "akamud.vscode-javascript-snippet-pack"
vscode "alefragnani.bookmarks"
vscode "alefragnani.project-manager"
vscode "alefragnani.rtf"
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "antfu.file-nesting"
vscode "antfu.icons-carbon"
vscode "antfu.vite"
vscode "arcticicestudio.nord-visual-studio-code"
vscode "arianjamasb.protein-viewer"
vscode "arrterian.nix-env-selector"
vscode "asvetliakov.vscode-neovim"
vscode "atishay-jain.all-autocomplete"
vscode "atlassian.atlascode"
vscode "aykutsarac.jsoncrack-vscode"
vscode "batisteo.vscode-django"
vscode "bbenoist.nix"
vscode "bierner.markdown-mermaid"
vscode "biomejs.biome"
vscode "bodil.file-browser"
vscode "bpruitt-goddard.mermaid-markdown-syntax-highlighting"
vscode "bradlc.vscode-tailwindcss"
vscode "buenon.scratchpads"
vscode "bysabi.prettier-vscode-standard"
vscode "catppuccin.catppuccin-vsc"
vscode "catppuccin.catppuccin-vsc-icons"
vscode "chaitanyashahare.lazygit"
vscode "charliermarsh.ruff"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "chrmarti.regex"
vscode "ckolkman.vscode-postgres"
vscode "clinyong.vscode-css-modules"
vscode "codezombiech.gitignore"
vscode "cstrap.flask-snippets"
vscode "cstrap.python-snippets"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "divyanshuagrawal.competitive-programming-helper"
vscode "donjayamanne.python-extension-pack"
vscode "dzhavat.bracket-pair-toggler"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "editorconfig.editorconfig"
vscode "emmanuelbeziat.vscode-great-icons"
vscode "enkia.tokyo-night"
vscode "equimper.react-native-react-redux"
vscode "ericsia.pythonsnippets3"
vscode "esbenp.prettier-vscode"
vscode "evan-buss.font-switcher"
vscode "file-icons.file-icons"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-rename-tag"
vscode "foxundermoon.shell-format"
vscode "github.codespaces"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.remotehub"
vscode "github.vscode-github-actions"
vscode "gitpod.gitpod-theme"
vscode "graphql.vscode-graphql-syntax"
vscode "gruntfuggly.todo-tree"
vscode "hashicorp.terraform"
vscode "honnamkuan.golang-snippets"
vscode "humao.rest-client"
vscode "ibm.output-colorizer"
vscode "idered.npm"
vscode "infeng.vscode-react-typescript"
vscode "infracost.infracost"
vscode "jacano.vscode-pnpm"
vscode "jacobdufault.fuzzy-search"
vscode "jasonnutter.search-node-modules"
vscode "jebbs.plantuml"
vscode "jithurjacob.nbpreviewer"
vscode "jnoortheen.nix-ide"
vscode "kahole.magit"
vscode "kamadorueda.alejandra"
vscode "kumar-harsh.graphql-for-vscode"
vscode "lastmile-ai.vscode-aiconfig"
vscode "launchdarklyofficial.launchdarkly"
vscode "leodevbro.blockman"
vscode "mathematic.vscode-latex"
vscode "mechatroner.rainbow-csv"
vscode "mermaidchart.vscode-mermaid-chart"
vscode "mgesbert.python-path"
vscode "mintlify.document"
vscode "mkhl.direnv"
vscode "monokai.theme-monokai-pro-vscode"
vscode "ms-azuretools.vscode-azureresourcegroups"
vscode "ms-azuretools.vscode-azurestorage"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-mssql.data-workspace-vscode"
vscode "ms-playwright.playwright"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.vscode-speech"
vscode "ms-vscode.vscode-typescript-next"
vscode "mtxr.sqltools"
vscode "mtxr.sqltools-driver-pg"
vscode "naumovs.color-highlight"
vscode "nefrob.vscode-just-syntax"
vscode "negokaz.live-server-preview"
vscode "orta.vscode-jest"
vscode "patbenatar.advanced-new-file"
vscode "pflannery.vscode-versionlens"
vscode "pinage404.nix-extension-pack"
vscode "pkief.material-product-icons"
vscode "planbcoding.vscode-react-refactor"
vscode "pmneo.tsimporter"
vscode "postman.postman-for-vscode"
vscode "pulkitgangwar.nextjs-snippets"
vscode "qassimfarid.ejs-language-support"
vscode "qcz.text-power-tools"
vscode "quicktype.quicktype"
vscode "redhat.vscode-yaml"
vscode "reditorsupport.r"
vscode "richie5um2.vscode-sort-json"
vscode "rooveterinaryinc.roo-cline"
vscode "rubymaniac.vscode-paste-and-indent"
vscode "rust-lang.rust-analyzer"
vscode "ryu1kn.partial-diff"
vscode "saoudrizwan.claude-dev"
vscode "sdras.night-owl"
vscode "semanticdiff.semanticdiff"
vscode "shinotatwu-ds.file-tree-generator"
vscode "sidneys1.gitconfig"
vscode "sidthesloth.html5-boilerplate"
vscode "siris01.catppuccin-theme"
vscode "skellock.just"
vscode "skyran.js-jsx-snippets"
vscode "sleistner.vscode-fileutils"
vscode "slevesque.vscode-multiclip"
vscode "sourcery.sourcery"
vscode "statelyai.stately-vscode"
vscode "stringham.move-ts"
vscode "sumneko.lua"
vscode "supabase.vscode-supabase-extension"
vscode "tamasfe.even-better-toml"
vscode "techer.open-in-browser"
vscode "terrastruct.d2"
vscode "tim-koehler.helm-intellisense"
vscode "tombonnike.vscode-status-bar-format-toggle"
vscode "tomoki1207.pdf"
vscode "tomrijndorp.find-it-faster"
vscode "tonka3000.raycast"
vscode "trunk.io"
vscode "usernamehw.errorlens"
vscode "vadimcn.vscode-lldb"
vscode "virgilsisoe.hammerspoon"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vivaxy.vscode-conventional-commits"
vscode "vscode-icons-team.vscode-icons"
vscode "vscodevim.vim"
vscode "vsls-contrib.gitdoc"
vscode "vspacecode.vspacecode"
vscode "vspacecode.whichkey"
vscode "wayou.vscode-todo-highlight"
vscode "whizkydee.material-palenight-theme"
vscode "xabikos.javascriptsnippets"
vscode "xabikos.reactsnippets"
vscode "yinfei.luahelper"
vscode "yoavbls.pretty-ts-errors"
vscode "yzhang.markdown-all-in-one"
vscode "zainchen.json"
vscode "zenstack.zenstack"
vscode "zhouronghui.propertylist"

# Newly added VSCode extensions (that were slated for uninstall):
vscode "42crunch.vscode-openapi"
vscode "4ops.terraform"
vscode "actboy168.lua-debug"
vscode "amazonemr.emr-tools"
vscode "antfu.browse-lite"
vscode "burkeholland.simple-react-snippets"
vscode "deerawan.vscode-dash"
vscode "donjayamanne.python-environment-manager"
vscode "eriklynd.json-tools"
vscode "firsttris.vscode-jest-runner"
vscode "frhtylcn.pythonsnippets"
vscode "george-alisson.html-preview-vscode"
vscode "golang.go"
vscode "jawandarajbir.react-vscode-extension-pack"
vscode "kamikillerto.vscode-colorize"
vscode "kevinrose.vsc-python-indent"
vscode "kisstkondoros.vscode-codemetrics"
vscode "leetcode.vscode-leetcode"
vscode "magicstack.magicpython"
vscode "mgmcdermott.vscode-language-babel"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.azure-account"
vscode "ms-vscode.azurecli"
vscode "ms-vscode.hexeditor"
vscode "ms-vscode.live-server"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-repositories"
vscode "ms-vscode.remote-server"
vscode "msjsdiag.vscode-react-native"
vscode "nrwl.angular-console"
vscode "oderwat.indent-rainbow"
vscode "openai.openai-chatgpt-adhoc"
vscode "pomdtr.excalidraw-editor"
vscode "prateekmahendrakar.prettyxml"
vscode "rubbersheep.gi"
vscode "ryanluker.vscode-coverage-gutters"
vscode "standard.vscode-standard"
vscode "styled-components.vscode-styled-components"
vscode "teamhub.teamhub"
vscode "teabyii.ayu"
vscode "tyriar.sort-lines"
vscode "wholroyd.jinja"
vscode "wix.vscode-import-cost"
vscode "formulahendry.code-runner"
vscode "ms-python.flake8"
vscode "ms-vscode.azure-repos"
vscode "rangav.vscode-thunder-client"
vscode "redocly.openapi-vs-code"
vscode "zhuangtongfa.material-theme"
vscode "ms-python.black-formatter"
vscode "ms-python.isort"
vscode "prisma.prisma"
vscode "redhat.vscode-xml"
vscode "ritwickdey.liveserver"

