brew "atuin", restart_service: :changed
brew "bat"
brew "biome"
brew "bitwarden-cli"
brew "curl"
brew "direnv"
brew "dust"
brew "fd"
brew "fx"
brew "fzf"
brew "gh"
brew "git-delta"
brew "glow"
brew "go"
brew "htop"
brew "httpie"
brew "jq"
brew "lazygit"
brew "mas"
brew "miller"
brew "neovim"
brew "postgresql@17", restart_service: :changed
brew "ruff"
brew "sd"
brew "starship"
brew "tldr"
brew "todoist"
brew "uv"
brew "volta"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "1password"
cask "betterdisplay"
cask "bitwarden"
cask "bruno"
cask "cardhop"
cask "chatgpt"
cask "claude"
cask "cleanshot"
cask "fantastical"
cask "figma"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-symbols-only-nerd-font"
cask "fork"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "hammerspoon"
cask "homerow"
cask "karabiner-elements"
cask "linear-linear"
cask "notion"
cask "obsidian"
cask "orbstack"
cask "postman"
cask "raycast"
cask "rippling"
cask "slack"
cask "spotify"
cask "superhuman"
cask "todoist"
cask "visual-studio-code"
cask "warp"
cask "zen-browser"
mas "Essentials", id: 1588151344
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
