#!/usr/bin/env zsh

# install.zsh - macOS dotfiles installation script
# Expects dotfiles repo to already be cloned at ~/dotfiles

set -euo pipefail



# -----------------------------------------------------------------------------
# Environment Configuration
# -----------------------------------------------------------------------------
export DOTFILES="${DOTFILES:-$HOME/dotfiles}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
export ZDOTDIR_TARGET="$DOTFILES/config/zsh"
export BACKUP_DIR="$HOME/.dotfiles_backup/$(date +%Y%m%d_%H%M%S)"



# Source utilities
if [[ ! -f "$DOTFILES/utils.sh" ]]; then
  echo "Error: utils.sh not found in $DOTFILES. Please ensure the dotfiles repository is properly cloned."
  exit 1
fi

. "$DOTFILES/utils.sh"


# -----------------------------------------------------------------------------
# Verify Repository Structure
# -----------------------------------------------------------------------------
verify_repo_structure() {
  info "Verifying dotfiles repository structure..."

  # Check if dotfiles directory exists
  if [[ ! -d "$DOTFILES" ]]; then
    error "Dotfiles directory not found at $DOTFILES"
    error "Please clone the repository first: git clone <repo-url> $DOTFILES"
    exit 1
  fi

  # Check if it's a git repository
  if [[ ! -d "$DOTFILES/.git" ]]; then
    error "The dotfiles directory is not a git repository"
    error "Please clone the repository properly: git clone <repo-url> $DOTFILES"
    exit 1
  fi

  # Check for critical directories and files
  local missing_items=()

  [[ ! -f "$DOTFILES/Brewfile" ]] && missing_items+=("Brewfile")
  [[ ! -d "$DOTFILES/config" ]] && missing_items+=("config dir")
  [[ ! -d "$DOTFILES/config/zsh" ]] && missing_items+=("config/zsh dir")
  [[ ! -f "$DOTFILES/config/zsh/.zshrc" ]] && missing_items+=("config/zsh/.zshrc file")
  [[ ! -f "$DOTFILES/config/zsh/.zprofile" ]] && missing_items+=("config/zsh/.zprofile file")
  [[ ! -d "$DOTFILES/config/nvim" ]] && missing_items+=("config/nvim dir")
  # [[ ! -f "$DOTFILES/config/zsh/.zshenv" ]] && missing_items+=("config/zsh/.zshenv file")

  if (( ${#missing_items[@]} > 0 )); then
    error "The dotfiles repository is missing critical components:"
    for item in "${missing_items[@]}"; do
      error "  - Missing $item"
    done
    error "Please ensure you've cloned the correct repository."
    exit 1
  fi

  success "Repository structure verified successfully"
}

# -----------------------------------------------------------------------------
# ZSH Setup
# -----------------------------------------------------------------------------
# # Setup minimal .zshenv
# setup_zshenv() {
#   local zshenv="$HOME/.zshenv"
#   info "Setting up .zshenv at $zshenv"
#
#   cat >"$zshenv" <<EOF
# # Minimal stub for Zsh
# export ZDOTDIR="$ZDOTDIR"
# [[ -f "$ZDOTDIR/.zshenv" ]] && source "$ZDOTDIR/.zshenv"
# EOF
#
#   success "Created $zshenv pointing to $ZDOTDIR"
# }

setup_zsh() {

  info "Setting up ZSH configuration..."

  # Backup existing .zshenv if it exists
  if [[ -f "$HOME/.zshenv" ]]; then
    backup_file "$HOME/.zshenv"
    rm -f "$HOME/.zshenv"
  fi

  # Create .zshenv in home directory pointing to dotfiles
  info "Creating .zshenv to point to dotfiles ZSH configuration"
  cat >"$HOME/.zshenv" <<EOF
# ZSH configuration bootstrapper
# Auto-generated by dotfiles installation script
export ZDOTDIR="$ZDOTDIR_TARGET"
[[ -f "$ZDOTDIR_TARGET/.zshenv" ]] && source "$ZDOTDIR_TARGET/.zshenv"
EOF

  chmod 644 "$HOME/.zshenv"
  success "Created $HOME/.zshenv pointing to $ZDOTDIR_TARGET"


  # # Ensure XDG config directory exists
  # ensure_dir "$XDG_CONFIG_HOME"
  
  # # Link ZSH config dir to XDG location for compatibility
  # if [[ -e "$XDG_CONFIG_HOME/zsh" || -L "$XDG_CONFIG_HOME/zsh" ]]; then
  #   backup_file "$XDG_CONFIG_HOME/zsh"
  #   rm -rf "$XDG_CONFIG_HOME/zsh"
  # fi
  #
  
  # # Create dir symlink (symlink .config/zsh --pointing--> dotfiles/config/zsh
  # ln -sf "$ZDOTDIR_TARGET" "$XDG_CONFIG_HOME/zsh"
  # success "Linked ZSH configuration to $XDG_CONFIG_HOME/zsh"
}

# -----------------------------------------------------------------------------
# Homebrew Setup
# -----------------------------------------------------------------------------
setup_homebrew() {
  info "Setting up Homebrew..."

  # if ! has_command brew; then
  if [[ ! -x /opt/homebrew/bin/brew ]]; then
    info "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    if is_apple_silicon; then
      eval "$(/opt/homebrew/bin/brew shellenv)"
    else
      eval "$(/usr/local/bin/brew shellenv)"
    fi
  else
    info "Homebrew is already installed"
  fi

  # Update Homebrew
  info "Updating Homebrew..."
  brew update

  # # Install from Brewfile
  # if [[ -f "$DOTFILES/Brewfile" ]]; then
  #   info "Installing packages from Brewfile..."
  #   # Ask user if they want to install all packages (could take time) or just essentials
  #   local answer
  #   read -q "answer? Install all Homebrew packages? This may take a while. [y/N] "
  #   echo ""

  #   if [[ "$answer" =~ ^[Yy]$ ]]; then
  #     # Full installation
  #     brew bundle install --file="$DOTFILES/Brewfile" --no-lock
  #   else
  #     # Install just essential packages for dotfiles to work
  #     info "Installing essential packages only..."
  #     brew install starship atuin zoxide bat zsh-syntax-highlighting zsh-autosuggestions fzf git
  #   fi
  # else
  #   warn "Brewfile not found at $DOTFILES/Brewfile"
  # fi
}

# -----------------------------------------------------------------------------
# CLI Tools Configuration
# -----------------------------------------------------------------------------
setup_cli_tools() {
  info "Setting up CLI tools configuration..."

  declare -A DOTFILES_TO_SYMLINK_MAP=(
  	# ["$DOTFILES/config/zsh/.zshrc"]="$ZDOTDIR_TARGET/.zshrc"
  	# ["$DOTFILES/config/zsh/.zprofile"]="$ZDOTDIR_TARGET/.zprofile"
  	# ["zsh/aliases.zsh"]="$ZDOTDIR/aliases.zsh"
  	# ["zsh/functions.zsh"]="$ZDOTDIR/functions.zsh"
  	# ["zsh/fzf.zsh"]="$ZDOTDIR/fzf.zsh"
  
  	["$DOTFILES/config/git/gitconfig"]="$HOME/.gitconfig"
  	["$DOTFILES/config/git/gitignore"]="$HOME/.gitignore1"
  
  	["$DOTFILES/config/starship.toml"]="$XDG_CONFIG_HOME/starship.toml"
  	["$DOTFILES/config/nvim"]="$XDG_CONFIG_HOME/nvim"
  	["$DOTFILES/config/ghostty"]="$XDG_CONFIG_HOME/ghostty"
  	["$DOTFILES/config/atuin"]="$XDG_CONFIG_HOME/atuin"
  	["$DOTFILES/config/bat"]="$XDG_CONFIG_HOME/bat"
  	["$DOTFILES/config/zellij"]="$XDG_CONFIG_HOME/zellij"
  	["$DOTFILES/config/espanso"]="$XDG_CONFIG_HOME/espanso"
  	["$DOTFILES/config/karabiner/karabiner.json"]="$XDG_CONFIG_HOME/karabiner/karabiner.json"
  
  	["$DOTFILES/config/vscode/settings.json"]="$XDG_CONFIG_HOME/vscode/settings.json"
  	["$DOTFILES/config/vscode/settings.json"]="$HOME/Library/Application Support/Cursor/User/settings.json"
  	["$DOTFILES/config/vscode/keybindings.json"]="$XDG_CONFIG_HOME/vscode/keybindings.json"
  	["$DOTFILES/config/vscode/keybindings.json"]="$HOME/Library/Application Support/Cursor/User/keybindings.json"
  	# $HOME/Library/Application Support/Code/User/settings.json
  	["$DOTFILES/config/cursor/settings.json"]="$XDG_CONFIG_HOME/cursor/settings.json"
  	["$DOTFILES/config/cursor/settings.json"]="$HOME/Library/Application Support/Cursor/User/settings.json"
  	["$DOTFILES/config/cursor/keybindings.json"]="$XDG_CONFIG_HOME/cursor/keybindings.json"
  	["$DOTFILES/config/cursor/keybindings.json"]="$HOME/Library/Application Support/Cursor/User/keybindings.json"
  	# $HOME/Library/Application Support/Cursor/User/settings.json
  
  	["$DOTFILES/config/hammerspoon"]="$HOME/.hammerspoon"
  
  	["$DOTFILES/config/ai/claude/claude_desktop_config.json"]="$HOME/Library/Application Support/Claude/claude_desktop_config.json"
  )


  ############
  # # Zsh-specific, not POSIX compliant
  # declare -A my_array
  # my_array=(
  #   [key1]=value1
  #   [key2]=value2
  #   [key3]=value3
  # )
  # for key in "${(@k)my_array}"; do
  #   echo "Key: $key, Value: ${my_array[$key]}"
  # done
  ############

  # Link (orig file) <- (new symlink)

  for key in "${(@k)DOTFILES_TO_SYMLINK_MAP}"; do
    # echo "Key: $key, Value: ${DOTFILES_TO_SYMLINK_MAP[$key]}"
    local k="$key"
    local v="${DOTFILES_TO_SYMLINK_MAP[$key]}"
    # echo "Key: $k, Value: $v"
    echo "[create link] orig dotfile ($k) <- ($v) new symlink"
    local parent_dir=$(basename "$v")

    ensure_dir $parent_dir
    if [[ -f "$k" ]]; then
	ln -sfw "$k" "$v"
        make_link "$DOTFILES/config/ghostty/config" "$XDG_CONFIG_HOME/ghostty/config"
    fi
  done


  # # Ghostty terminal
  # declare -A 
  # if [[ -d "$DOTFILES/config/ghostty" ]]; then
  #   ensure_dir "$XDG_CONFIG_HOME/ghostty"
  #
  #   if [[ -f "$DOTFILES/config/ghostty/config" ]]; then
  #     make_link "$DOTFILES/config/ghostty/config" "$XDG_CONFIG_HOME/ghostty/config"
  #   fi
  # fi
  #
  #
  # # Starship prompt
  # if [[ -f "$DOTFILES/config/starship.toml" ]]; then
  #   ensure_dir "$XDG_CONFIG_HOME"
  #   make_link "$DOTFILES/config/starship.toml" "$XDG_CONFIG_HOME/starship.toml"
  # fi
  #
  # # Atuin shell history
  # # TODO: fix
  # # if [[ -d "$DOTFILES/config/atuin" ]]; then
  # #   ensure_dir "$XDG_CONFIG_HOME/atuin"
  # #   make_link "$DOTFILES/config/atuin/config.toml" "$XDG_CONFIG_HOME/atuin/config.toml"
  # # fi
  #
  # # # Bat (cat replacement)
  # # if [[ -d "$DOTFILES/config/bat" ]]; then
  # #   ensure_dir "$XDG_CONFIG_HOME/bat"
  # #   make_link "$DOTFILES/config/bat/config" "$XDG_CONFIG_HOME/bat/config"
  # # fi
  #
  #
  # # Neovim
  # if [[ -d "$DOTFILES/config/nvim" ]]; then
  #   # ensure_dir "$XDG_CONFIG_HOME/nvim"
  #   ln -sf "$DOTFILES/config/nvim" "$XDG_CONFIG_HOME/nvim"
  # fi

 # # Zellij terminal multiplexer
  # if [[ -d "$DOTFILES/config/zellij" ]]; then
  #   ensure_dir "$XDG_CONFIG_HOME/zellij"
  #   make_link "$DOTFILES/config/zellij/config.kdl" "$XDG_CONFIG_HOME/zellij/config.kdl"
  # fi
  
  # Neovim
  # ln -sf "$DOTFILES/config/nvim" "$XDG_CONFIG_HOME/nvim"


  # if [[ -d "$DOTFILES/config/nvim" ]]; then
  #   ensure_dir "$XDG_CONFIG_HOME/nvim"

  #   # Link critical Neovim files
  #   if [[ -f "$DOTFILES/config/nvim/init.lua" ]]; then
  #     make_link "$DOTFILES/config/nvim/init.lua" "$XDG_CONFIG_HOME/nvim/init.lua"
  #   fi

  #   # Link other Neovim config files
  #   for file in "$DOTFILES/config/nvim/"*.{json,md,vim}; do
  #     if [[ -f "$file" ]]; then
  #       local filename=$(basename "$file")
  #       make_link "$file" "$XDG_CONFIG_HOME/nvim/$filename"
  #     fi
  #   done

  #   # Recursively link lua directory if it exists
  #   if [[ -d "$DOTFILES/config/nvim/lua" ]]; then
  #     ensure_dir "$XDG_CONFIG_HOME/nvim/lua"

  #     # Find all lua files and link them
  #     find "$DOTFILES/config/nvim/lua" -type f -name "*.lua" | while read -r file; do
  #       local rel_path="${file#$DOTFILES/config/nvim/}"
  #       local target_dir="$(dirname "$XDG_CONFIG_HOME/nvim/$rel_path")"
  #       ensure_dir "$target_dir"
  #       make_link "$file" "$XDG_CONFIG_HOME/nvim/$rel_path"
  #     done
  #   fi
  # fi

  # # Espanso text expander
  # if [[ -d "$DOTFILES/config/espanso" ]]; then
  #   ensure_dir "$XDG_CONFIG_HOME/espanso/match"
  #   ensure_dir "$XDG_CONFIG_HOME/espanso/config"
  #
  #   if [[ -f "$DOTFILES/config/espanso/match/base.yml" ]]; then
  #     make_link "$DOTFILES/config/espanso/match/base.yml" "$XDG_CONFIG_HOME/espanso/match/base.yml"
  #   fi
  #
  #   if [[ -f "$DOTFILES/config/espanso/config/default.yml" ]]; then
  #     make_link "$DOTFILES/config/espanso/config/default.yml" "$XDG_CONFIG_HOME/espanso/config/default.yml"
  #   fi
  # fi
}

# -----------------------------------------------------------------------------
# GUI Apps Configuration
# -----------------------------------------------------------------------------
# setup_gui_apps() {
#   info "Setting up GUI applications configuration..."
#
#   # Karabiner (keyboard customization)
#   if [[ -d "$DOTFILES/config/karabiner" ]]; then
#     ensure_dir "$XDG_CONFIG_HOME/karabiner"
#     make_link "$DOTFILES/config/karabiner/karabiner.json" "$XDG_CONFIG_HOME/karabiner/karabiner.json"
#   fi
#
#   # # VS Code
#   # if [[ -d "$DOTFILES/config/vscode" ]]; then
#   #   ensure_dir "$HOME/Library/Application Support/Code/User"
#   #   make_link "$DOTFILES/config/vscode/settings.json" "$HOME/Library/Application Support/Code/User/settings.json"
#   #   make_link "$DOTFILES/config/vscode/keybindings.json" "$HOME/Library/Application Support/Code/User/keybindings.json"
#   # fi
#   #
#   # Cursor (VS Code-based editor)
#   if [[ -d "$DOTFILES/config/cursor" ]]; then
#     ensure_dir "$HOME/Library/Application Support/Cursor/User"
#     make_link "$DOTFILES/config/cursor/settings.json" "$HOME/Library/Application Support/Cursor/User/settings.json"
#     make_link "$DOTFILES/config/cursor/keybindings.json" "$HOME/Library/Application Support/Cursor/User/keybindings.json"
#   fi
#
#   # Hammerspoon
#   if [[ -d "$DOTFILES/config/hammerspoon" ]]; then
#     ln -sf "$DOTFILES/config/hammerspoon" "$HOME/.hammerspoon"
#     # ensure_dir "$HOME/.hammerspoon"
#     # make_link "$DOTFILES/config/hammerspoon/init.lua" "$HOME/.hammerspoon/init.lua"
#   fi
#
#   # Claude Desktop
#   if [[ -d "$DOTFILES/config/ai/claude" ]]; then
#     ensure_dir "$HOME/Library/Application Support/Claude"
#     make_link "$DOTFILES/config/ai/claude/claude_desktop_config.json" "$HOME/Library/Application Support/Claude/claude_desktop_config.json"
#   fi
# }

# -----------------------------------------------------------------------------
# macOS System Preferences
# -----------------------------------------------------------------------------
function setup_macos_preferences() {
  info "Configuring macOS system preferences..."

  # Faster key repeat
  defaults write NSGlobalDomain KeyRepeat -int 2
  defaults write NSGlobalDomain InitialKeyRepeat -int 15

  # Disable press-and-hold for keys in favor of key repeat
  defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

  # Always show file extensions
  defaults write NSGlobalDomain AppleShowAllExtensions -bool true

  # Don't write .DS_Store files on network drives
  defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

  # Dock settings
  defaults write com.apple.dock autohide -bool true
  defaults write com.apple.dock autohide-delay -float 0
  defaults write com.apple.dock show-recents -bool false

  # Enable trackpad tap to click
  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true

  # Finder settings
  defaults write com.apple.finder AppleShowAllFiles -bool true
  defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
  defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
  defaults write com.apple.finder ShowPathbar -bool true
  defaults write com.apple.finder ShowStatusBar -bool true
  defaults write com.apple.finder _FXSortFoldersFirst -bool true

  # Restart affected applications
  for app in "Finder" "Dock"; do
    killall "$app" &>/dev/null || true
  done

  success "macOS preferences configured"
}

# -----------------------------------------------------------------------------
# Main Setup Function
# -----------------------------------------------------------------------------
function main() {
  info "Starting dotfiles setup for macOS..."

  # Check if running on macOS
  if ! is_macos; then
    error "This script is designed for macOS only."
    exit 1
  fi

  # Verify repository structure first
  verify_repo_structure

  # Show install plan
  info "Installation plan:"
  echo "  ✓ Set up ZSH configuration"
  [[ "$NO_BREW" == "false" ]] && echo "  ✓ Set up Homebrew packages"
  echo "  ✓ Configure CLI tools"
  echo "  ✓ Configure GUI applications"
  [[ "$NO_MACOS" == "false" ]] && echo "  ✓ Configure macOS preferences"
  [[ "$MINIMAL" == "false" ]] && echo "  ✓ Set up development environment"
  [[ "$MINIMAL" == "false" ]] && echo "  ✓ Configure optional tools"
  echo ""

  # Ask for confirmation
  # local answer
  # read -q "answer?Continue with installation? [Y/n] "
  # echo ""

  # if [[ ! "$answer" =~ ^[Yy]$ && ! -z "$answer" ]]; then
  #   info "Installation cancelled by user"
  #   exit 0
  # fi

  # Start installation timer
  local start_time=$(date +%s)

  # Create XDG directories
  ensure_dir "$XDG_CONFIG_HOME"
  ensure_dir "$XDG_CACHE_HOME"
  ensure_dir "$XDG_DATA_HOME"
  ensure_dir "$XDG_STATE_HOME"

  # unlink ALL existing symlinks in ~/.config/*
  unlink_all_in_dir "$XDG_CONFIG_HOME"

  # Setup components
  setup_zsh

  if [[ "$NO_BREW" == "false" ]]; then
    setup_homebrew
  else
    info "Skipping Homebrew setup (--no-brew flag used)"
  fi

  setup_cli_tools

  if [[ "$NO_MACOS" == "false" ]]; then
    setup_macos_preferences
  else
    info "Skipping macOS preferences (--no-macos flag used)"
  fi

  # Calculate time taken
  local end_time=$(date +%s)
  local time_taken=$((end_time - start_time))
  local minutes=$((time_taken / 60))
  local seconds=$((time_taken % 60))

  success "Dotfiles setup complete! 🎉"
  info "Time taken: ${minutes}m ${seconds}s"

  if [[ -d "$BACKUP_DIR" && "$(ls -A "$BACKUP_DIR" 2>/dev/null)" ]]; then
    local backup_size=$(du -sh "$BACKUP_DIR" | cut -f1)
    info "Backup created at $BACKUP_DIR ($backup_size)"
  fi

  info "Please log out and log back in, or restart your computer for all changes to take effect."
  info "To finish setting up your shell, run: exec zsh"
}

# Parse command-line arguments
function parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --no-brew)
        NO_BREW=true
        shift
        ;;
      --no-macos)
        NO_MACOS=true
        shift
        ;;
      --minimal)
        MINIMAL=true
        shift
        ;;
      --help)
        echo "Usage: $0 [options]"
        echo "Options:"
        echo "  --no-brew     Skip Homebrew installation and updates"
        echo "  --no-macos    Skip macOS preferences configuration"
        echo "  --minimal     Install only essential configurations"
        echo "  --help        Show this help message"
        exit 0
        ;;
      *)
        echo "Unknown option: $1"  # Replace with your warning method
        shift
        ;;
    esac
  done
}

# Initialize optional flags
NO_BREW=false
NO_MACOS=false
MINIMAL=false

# Run if script is executed directly
# if [[ "${(%):-%x}" == "${0:A}" ]]; then
#   parse_args "$@"
#   main "$@"
# fi
#

parse_args "$@"
main "$@"
