# Unified AI Agent Configuration
# Manages Claude Code CLI, Gemini CLI, and Antigravity IDE configs
# Single source of truth for AGENT.md, MCP servers, commands, skills
{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib) mkEnableOption mkIf;
  agentsDir = "${config.home.homeDirectory}/dotfiles/config/agents";
in
{
  options.modules.home.apps.agents = {
    enable = mkEnableOption "Unified AI agent configuration";
  };

  config = mkIf config.modules.home.apps.agents.enable {
    # jq required for JSON merging
    home.packages = [ pkgs.jq ];

    # Static configs (immutable - symlinked)
    home.file = {
      # ========================================
      # Claude Code CLI
      # ========================================
      # NOTE: .claude/settings.json and .claude/agents are now managed by modules/home/apps/claude.nix
      ".claude/CLAUDE.md".source = config.lib.file.mkOutOfStoreSymlink "${agentsDir}/AGENTS.md";
      ".claude/commands".source = config.lib.file.mkOutOfStoreSymlink "${agentsDir}/commands";
      # .claude/agents is now generated by Quality System (modules/home/apps/claude.nix)
      # .claude/skills is now generated by Quality System (modules/home/apps/claude.nix)
      ".claude/rules".source = config.lib.file.mkOutOfStoreSymlink "${agentsDir}/rules";
      ".claude/memory".source = config.lib.file.mkOutOfStoreSymlink "${agentsDir}/memory";

      # ========================================
      # Gemini CLI
      # ========================================
      ".gemini/GEMINI.md".source = config.lib.file.mkOutOfStoreSymlink "${agentsDir}/AGENTS.md";
      ".gemini/settings.json".source =
        config.lib.file.mkOutOfStoreSymlink "${agentsDir}/settings/gemini.json";
      ".gemini/rules".source = config.lib.file.mkOutOfStoreSymlink "${agentsDir}/rules";
      ".gemini/memory".source = config.lib.file.mkOutOfStoreSymlink "${agentsDir}/memory";
      # MCP servers generated by modules/home/apps/claude.nix (single source of truth)
      ".gemini/mcp-servers.json".source =
        config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.config/claude/mcp-servers.json";

      # ========================================
      # Antigravity IDE
      # ========================================
      # MCP servers generated by modules/home/apps/claude.nix (single source of truth)
      ".gemini/antigravity/mcp_config.json".source =
        config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.config/claude/mcp-servers.json";
    };

    # Shell aliases for project setup
    programs.zsh.shellAliases = {
      agent-setup = "ln -sf ${agentsDir}/AGENTS.md ./CLAUDE.md && ln -sf ${agentsDir}/AGENTS.md ./GEMINI.md && echo 'Agent context linked'";
      agent-clean = "rm -f ./CLAUDE.md ./GEMINI.md && echo 'Agent context removed'";
    };

    # Full Nix generation for ~/.claude.json (no merge pattern - simpler and more reliable)
    # userID is preserved in ~/.config/claude/user-id if it exists
    home.activation.agentsConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      CLAUDE_DIR="$HOME/.claude"
      MCP_FILE="$HOME/.claude.json"
      BACKUP_DIR="$CLAUDE_DIR/backups"
      USER_ID_FILE="$HOME/.config/claude/user-id"
      # MCP servers generated by modules/home/apps/claude.nix (single source of truth)
      SOURCE_MCP="$HOME/.config/claude/mcp-servers.json"

      $DRY_RUN_CMD mkdir -p "$CLAUDE_DIR" "$CLAUDE_DIR/skills" "$BACKUP_DIR"
      $DRY_RUN_CMD mkdir -p "$HOME/.gemini/antigravity"
      $DRY_RUN_CMD mkdir -p "$HOME/.config/claude"

      # Remove old settings.json if it exists (now managed by symlink)
      if [ -f "$CLAUDE_DIR/settings.json" ] && [ ! -L "$CLAUDE_DIR/settings.json" ]; then
        $DRY_RUN_CMD cp "$CLAUDE_DIR/settings.json" "$BACKUP_DIR/settings.$(date +%Y%m%d%H%M%S).json"
        $DRY_RUN_CMD rm "$CLAUDE_DIR/settings.json"
        echo "Backed up and removed old settings.json (now symlinked)"
      fi

      # ========================================
      # Claude Code: ~/.claude.json - FULL GENERATION (not merge)
      # ========================================
      # Extract and preserve userID if it exists (Claude's analytics identifier)
      if [ -f "$MCP_FILE" ] && [ ! -f "$USER_ID_FILE" ]; then
        if EXISTING_ID=$(${pkgs.jq}/bin/jq -r '.userID // empty' "$MCP_FILE"); then
          if [ -n "$EXISTING_ID" ]; then
            echo "$EXISTING_ID" > "$USER_ID_FILE"
            echo "Preserved userID to $USER_ID_FILE"
          fi
        else
          echo "Note: Could not parse existing ~/.claude.json for userID extraction"
        fi
      fi

      # Backup existing config before overwriting
      if [ -f "$MCP_FILE" ]; then
        $DRY_RUN_CMD cp "$MCP_FILE" "$BACKUP_DIR/claude.$(date +%Y%m%d%H%M%S).json"
      fi

      # Generate fresh ~/.claude.json from Nix source (single source of truth)
      if [ -f "$SOURCE_MCP" ]; then
        if [ -f "$USER_ID_FILE" ]; then
          # Include preserved userID
          USER_ID=$(cat "$USER_ID_FILE")
          ${pkgs.jq}/bin/jq -n \
            --arg userid "$USER_ID" \
            --argjson servers "$(cat "$SOURCE_MCP")" \
            '{userID: $userid, mcpServers: $servers}' > "$MCP_FILE"
        else
          # Generate without userID (Claude will create one on first run)
          ${pkgs.jq}/bin/jq -n \
            --argjson servers "$(cat "$SOURCE_MCP")" \
            '{mcpServers: $servers}' > "$MCP_FILE"
        fi
        echo "Generated ~/.claude.json from Nix source ($(${pkgs.jq}/bin/jq '.mcpServers | keys | length' "$MCP_FILE") servers)"
      else
        echo "WARNING: Source MCP config not found at $SOURCE_MCP"
      fi

      # Cleanup old backups (keep last 5)
      # shellcheck disable=SC2012 - ls sorted by time is intentional for backup rotation
      if [ -d "$BACKUP_DIR" ]; then
        BACKUP_COUNT=$(find "$BACKUP_DIR" -maxdepth 1 -name "*.json" -type f | wc -l)
        if [ "$BACKUP_COUNT" -gt 5 ]; then
          ls -t "$BACKUP_DIR"/*.json | tail -n +6 | xargs -r rm -f
        fi
      fi

      # Ensure session log exists
      $DRY_RUN_CMD touch "$CLAUDE_DIR/session.log"

      echo "Unified agent configuration ready (Claude Code + Gemini CLI + Antigravity)"
    '';
  };
}
