# Unified AI Agent Configuration
# Manages Claude Code CLI, Gemini CLI, and Antigravity IDE configs
# Single source of truth for AGENT.md, MCP servers, commands, skills
{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib) mkEnableOption mkIf;
  agentsDir = "${config.home.homeDirectory}/dotfiles/config/agents";
in
{
  options.modules.home.apps.agents = {
    enable = mkEnableOption "Unified AI agent configuration";
  };

  config = mkIf config.modules.home.apps.agents.enable {
    # jq required for JSON merging
    home.packages = [ pkgs.jq ];

    # Static configs (immutable - symlinked)
    home.file = {
      # ========================================
      # Claude Code CLI
      # ========================================
      # NOTE: .claude/settings.json and .claude/agents are now managed by modules/home/apps/claude.nix
      ".claude/CLAUDE.md".source = config.lib.file.mkOutOfStoreSymlink "${agentsDir}/AGENTS.md";
      ".claude/commands".source = config.lib.file.mkOutOfStoreSymlink "${agentsDir}/commands";
      # .claude/agents is now generated by Quality System (modules/home/apps/claude.nix)
      # .claude/skills is now generated by Quality System (modules/home/apps/claude.nix)
      ".claude/rules".source = config.lib.file.mkOutOfStoreSymlink "${agentsDir}/rules";
      ".claude/memory".source = config.lib.file.mkOutOfStoreSymlink "${agentsDir}/memory";

      # ========================================
      # Gemini CLI
      # ========================================
      ".gemini/GEMINI.md".source = config.lib.file.mkOutOfStoreSymlink "${agentsDir}/AGENTS.md";
      ".gemini/settings.json".source =
        config.lib.file.mkOutOfStoreSymlink "${agentsDir}/settings/gemini.json";
      ".gemini/rules".source = config.lib.file.mkOutOfStoreSymlink "${agentsDir}/rules";
      ".gemini/memory".source = config.lib.file.mkOutOfStoreSymlink "${agentsDir}/memory";
      # MCP servers generated by modules/home/apps/claude.nix (single source of truth)
      ".gemini/mcp-servers.json".source =
        config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.config/claude/mcp-servers.json";

      # ========================================
      # Antigravity IDE
      # ========================================
      # MCP servers generated by modules/home/apps/claude.nix (single source of truth)
      ".gemini/antigravity/mcp_config.json".source =
        config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.config/claude/mcp-servers.json";
    };

    # Shell aliases for project setup
    programs.zsh.shellAliases = {
      agent-setup = "ln -sf ${agentsDir}/AGENTS.md ./CLAUDE.md && ln -sf ${agentsDir}/AGENTS.md ./GEMINI.md && echo 'Agent context linked'";
      agent-clean = "rm -f ./CLAUDE.md ./GEMINI.md && echo 'Agent context removed'";
    };

    # Pure declarative generation of ~/.claude.json
    # All onboarding flags included to skip interactive prompts
    # userID managed by sops-nix (decrypted to ~/.config/claude/user-id)
    home.activation.agentsConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      CLAUDE_DIR="$HOME/.claude"
      MCP_FILE="$HOME/.claude.json"
      BACKUP_DIR="$CLAUDE_DIR/backups"
      # sops-nix decrypts this from secrets/darwin.yaml
      USER_ID_FILE="$HOME/.config/claude/user-id"
      # MCP servers generated by modules/home/apps/claude.nix (single source of truth)
      SOURCE_MCP="$HOME/.config/claude/mcp-servers.json"

      $DRY_RUN_CMD mkdir -p "$CLAUDE_DIR" "$CLAUDE_DIR/skills" "$BACKUP_DIR"
      $DRY_RUN_CMD mkdir -p "$HOME/.gemini/antigravity"
      $DRY_RUN_CMD mkdir -p "$HOME/.config/claude"

      # Remove old settings.json if it exists (now managed by symlink)
      if [ -f "$CLAUDE_DIR/settings.json" ] && [ ! -L "$CLAUDE_DIR/settings.json" ]; then
        $DRY_RUN_CMD cp "$CLAUDE_DIR/settings.json" "$BACKUP_DIR/settings.$(date +%Y%m%d%H%M%S).json"
        $DRY_RUN_CMD rm "$CLAUDE_DIR/settings.json"
        echo "Backed up and removed old settings.json (now symlinked)"
      fi

      # ========================================
      # Claude Code: ~/.claude.json - PURE DECLARATIVE GENERATION
      # ========================================
      # Read userID from sops-nix decrypted secret
      USER_ID=""
      if [ -f "$USER_ID_FILE" ]; then
        USER_ID=$(cat "$USER_ID_FILE")
      fi

      # Auto-detect Claude Code version for lastOnboardingVersion
      CLAUDE_VERSION=$(claude --version 2>/dev/null | head -1 | sed 's/[^0-9.]//g' || echo "2.0.76")

      # Backup existing config before overwriting
      if [ -f "$MCP_FILE" ]; then
        $DRY_RUN_CMD cp "$MCP_FILE" "$BACKUP_DIR/claude.$(date +%Y%m%d%H%M%S).json"
      fi

      # Generate complete ~/.claude.json with all onboarding flags
      # This eliminates all interactive prompts on startup
      if [ -f "$SOURCE_MCP" ]; then
        ${pkgs.jq}/bin/jq -n \
          --arg userID "$USER_ID" \
          --arg version "$CLAUDE_VERSION" \
          --argjson servers "$(cat "$SOURCE_MCP")" \
          '{
            userID: $userID,
            numStartups: 999,
            hasCompletedOnboarding: true,
            lastOnboardingVersion: $version,
            bypassPermissionsModeAccepted: true,
            shiftEnterKeyBindingInstalled: true,
            sonnet45MigrationComplete: true,
            opus45MigrationComplete: true,
            thinkingMigrationComplete: true,
            officialMarketplaceAutoInstallAttempted: true,
            officialMarketplaceAutoInstalled: true,
            mcpServers: $servers
          }' > "$MCP_FILE"
        echo "Generated ~/.claude.json (pure declarative, version: $CLAUDE_VERSION, $(${pkgs.jq}/bin/jq '.mcpServers | keys | length' "$MCP_FILE") servers)"
      else
        echo "WARNING: Source MCP config not found at $SOURCE_MCP"
      fi

      # Cleanup old backups (keep last 5)
      # shellcheck disable=SC2012 - ls sorted by time is intentional for backup rotation
      if [ -d "$BACKUP_DIR" ]; then
        BACKUP_COUNT=$(find "$BACKUP_DIR" -maxdepth 1 -name "*.json" -type f | wc -l)
        if [ "$BACKUP_COUNT" -gt 5 ]; then
          ls -t "$BACKUP_DIR"/*.json | tail -n +6 | xargs -r rm -f
        fi
      fi

      # Ensure session log exists
      $DRY_RUN_CMD touch "$CLAUDE_DIR/session.log"

      echo "Unified agent configuration ready (Claude Code + Gemini CLI + Antigravity)"
    '';
  };
}
