-----------------------------------------------------------------------------------
-- Neovim Configuration (init.lua) - Based on LazyVim (Updated February 2025)
-----------------------------------------------------------------------------------
-- 
-- This file serves as the entry point for the Neovim configuration.
-- LazyVim manages the loading of all plugins and configurations.
--
-- Key resources:
-- * Lua for Neovim: https://neovim.io/doc/user/lua.html
-- * LazyVim Documentation: https://www.lazyvim.org/
--
-- Directory structure:
-- * lua/config/: Core configuration files
--   - lazy.lua: Plugin manager setup (loaded here)
--   - options.lua: Vim options (loaded on startup)
--   - keymaps.lua: Custom key mappings (loaded on VeryLazy)
--   - autocmds.lua: Auto commands (loaded on VeryLazy)
-- * lua/plugins/: Custom plugin configurations (loaded by lazy.nvim)
--
-- LazyVim loads its default configurations before your custom ones,
-- allowing you to override them as needed.

-- Bootstrap lazy.nvim, LazyVim and plugins
require("config.lazy")
