
# ~/dotfiles/home/zsh/zshrc - Interactive shell configuration
source "${ZDOTDIR}/env.zsh"
source "${ZDOTDIR}/completions.zsh"
source "${ZDOTDIR}/aliases.zsh"
source "${ZDOTDIR}/functions.zsh"
source "${ZDOTDIR}/macos.zsh"

# History configuration
HISTFILE="${XDG_DATA_HOME}/zsh/history"
HISTSIZE=1000000
SAVEHIST=1000000

setopt EXTENDED_HISTORY
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY

# Directory options
setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT
setopt EXTENDED_GLOB

# Tool initializations
has_command starship && eval "$(starship init zsh)"
has_command zoxide && eval "$(zoxide init zsh)"
has_command atuin && eval "$(atuin init zsh)"
has_command direnv && eval "$(direnv hook zsh)"

# Key bindings
bindkey -v  # Vi mode
bindkey '^R' _atuin_search_widget
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^H' backward-kill-word
bindkey '^[[3;5~' kill-word

