# Kanata keyboard remapper - system daemon
# Requires Karabiner driver: brew install karabiner-elements
#
# IMPORTANT: macOS TCC requires Input Monitoring permission even for root.
# Add /usr/local/bin/kanata to System Settings > Privacy & Security > Input Monitoring
#
# Config is generated by home-manager (modules/home/apps/kanata.nix)
# This module manages the launchd daemon and auto-restart on switch
{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib) mkEnableOption mkIf;

  # Stable path for Input Monitoring (survives Nix rebuilds)
  # User adds this ONCE to Input Monitoring, symlink updated on each rebuild
  stableKanataPath = "/usr/local/bin/kanata";
in
{
  options.modules.darwin.kanata = {
    enable = mkEnableOption "Kanata keyboard remapper daemon";
  };

  config = mkIf config.modules.darwin.kanata.enable {
    # System-level LaunchDaemon (runs as root)
    # Use kanata-with-cmd to enable Command key in combinations (for Meh/Hyper)
    # Uses stable symlink path so Input Monitoring permission persists across rebuilds
    launchd.daemons.kanata = {
      serviceConfig = {
        Label = "org.kanata.daemon";
        ProgramArguments = [
          stableKanataPath
          "--cfg"
          "/Users/${config.system.primaryUser}/.config/kanata/kanata.kbd"
        ];
        RunAtLoad = true;
        KeepAlive = true;
        StandardOutPath = "/tmp/kanata.log";
        StandardErrorPath = "/tmp/kanata.err";
      };
    };

    # Create stable symlink and restart daemon after activation
    # The symlink at /usr/local/bin/kanata persists Input Monitoring permission
    # while pointing to the current Nix store path
    system.activationScripts.postActivation.text = ''
      echo "Updating Kanata symlink and restarting daemon..."

      # Create stable symlink (survives Nix rebuilds, keeps Input Monitoring permission)
      mkdir -p /usr/local/bin
      ln -sf "${pkgs.kanata-with-cmd}/bin/kanata" "${stableKanataPath}"

      # Restart daemon to pick up any config changes (detached, logs go to /tmp/kanata.*)
      /bin/launchctl kickstart -k system/org.kanata.daemon &

      # Check if Input Monitoring is configured (query may fail if not root, treat as unconfigured)
      tcc_result=$(sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" \
        "SELECT 1 FROM access WHERE client='${stableKanataPath}' AND service='kTCCServiceListenEvent'" 2>&1) || tcc_result=""
      if ! echo "$tcc_result" | grep -q 1; then
        echo ""
        echo "╔═══════════════════════════════════════════════════════════════════╗"
        echo "║  MANUAL STEP REQUIRED: Add Kanata to Input Monitoring             ║"
        echo "║                                                                   ║"
        echo "║  System Settings > Privacy & Security > Input Monitoring         ║"
        echo "║  Click '+' and add: /usr/local/bin/kanata                         ║"
        echo "║                                                                   ║"
        echo "║  This only needs to be done ONCE (persists across rebuilds)       ║"
        echo "╚═══════════════════════════════════════════════════════════════════╝"
        echo ""
      fi
    '';
  };
}
