openapi: 3.0.0
info:
  title: noggin-api-orig
  version: 1.0.0
paths:
 
servers:
  - url: http://localhost:8080
components:
  schemas:
    create_a_one-time_password_for_login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    verify_otp_and_get_authentication_tokens:
      type: object
      properties:
        email:
          type: string
        otp:
          type: string
  requestBodies:
    create_a_one-time_password_for_login:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create_a_one-time_password_for_login'
      description: ''
      required: true
    verify_otp_and_get_authentication_tokens:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/verify_otp_and_get_authentication_tokens'
      description: ''
      required: true
  securitySchemes: {}
