# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Starship Terminal Prompt Configuration
# Optimized for macOS Apple Silicon (2025)
# https://starship.rs/config/

# General Prompt Configuration
# ===========================
format = '$all'

# Add newline before prompt
add_newline = true

# Set timeout for commands (faster on Apple Silicon)
command_timeout = 500 # milliseconds

# Set the shell's scan_timeout (Apple Silicon can handle faster scans)
scan_timeout = 30 # milliseconds

# Disable the terminal's line_break to create a cleaner look
[line_break]
    disabled = false
