/**
 * Codex config.toml generator (Effect-TS native).
 *
 * Emits `generated/codex/config.toml` consumed by the activation hook in
 * `modules/home/apps/codex.nix`, which copies it byte-for-byte into each
 * `~/.codex-max-N/config.toml`. REF_API_KEY is NOT baked into the file —
 * the `cx` recipe exports it from `~/.config/mcp/ref-api-key` at
 * invocation time, and Codex resolves it via `bearer_token_env_var`.
 *
 * Schema reference: https://developers.openai.com/codex/config-reference
 *
 * Sections emitted:
 *   - top-level `model`, `model_provider`, `approval_policy`, `sandbox_mode`
 *   - `[features]`             enable codex_hooks, multi_agent, web_search
 *   - `[shell_environment_policy]`
 *   - `[mcp_servers.<name>]`   one block per MCP server (ref only today)
 *   - `[[hooks.<Event>]]`      from CODEX_HOOK_DEFINITIONS
 *   - `[agents]`               max_threads, max_depth, runtime caps
 *   - `[history]`              size cap
 *   - `[tui]`                  file_opener
 */

import * as path from 'node:path'
import { FileSystem } from '@effect/platform'
import { Effect } from 'effect'
import {
  ALL_CODEX_HOOK_EVENTS,
  CODEX_HOOK_DEFINITIONS,
  type CodexHookEvent,
  type CodexMatcherHookGroup,
} from '../../hooks/codex-definitions'

// =============================================================================
// Defaults
// =============================================================================

const CODEX_MODEL = 'gpt-5.3-codex'
const CODEX_MODEL_PROVIDER = 'openai'
const CODEX_SANDBOX_MODE = 'workspace-write'
const CODEX_APPROVAL_POLICY = 'on-request'

// =============================================================================
// TOML emitters
// =============================================================================

/** TOML string-literal quoting. Codex uses standard TOML 1.0 strings. */
const tomlString = (s: string): string => {
  if (!s.includes('\\') && !s.includes('"')) return `"${s}"`
  // Escape backslashes and double quotes
  return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

const emitHookBlocks = (event: CodexHookEvent, groups: readonly CodexMatcherHookGroup[]): string => {
  if (groups.length === 0) return ''
  const lines: string[] = []
  for (const group of groups) {
    if (group.hooks.length === 0) continue
    for (const hook of group.hooks) {
      lines.push(`[[hooks.${event}]]`)
      if (group.matcher !== undefined) {
        lines.push(`matcher = ${tomlString(group.matcher)}`)
      }
      lines.push('[[hooks.' + event + '.hooks]]')
      lines.push(`type = ${tomlString(hook.type)}`)
      lines.push(`command = ${tomlString(hook.command)}`)
      lines.push(`timeout = ${hook.timeout}`)
      if (hook.statusMessage !== undefined) {
        lines.push(`statusMessage = ${tomlString(hook.statusMessage)}`)
      }
      lines.push('')
    }
  }
  return lines.join('\n')
}

// =============================================================================
// Generator
// =============================================================================

const generateConfigToml = (): string => {
  const lines: string[] = []

  // --- Header
  lines.push('# Codex CLI global config.')
  lines.push('# Generated by config/quality/src/generators/codex/. DO NOT EDIT.')
  lines.push('# Activation hook in modules/home/apps/codex.nix deploys this file')
  lines.push('# byte-for-byte to each ~/.codex-max-N/config.toml. REF_API_KEY is')
  lines.push('# exported by the `cx` recipe at invocation time, not baked here.')
  lines.push('')

  // --- Top-level
  lines.push(`model = ${tomlString(CODEX_MODEL)}`)
  lines.push(`model_provider = ${tomlString(CODEX_MODEL_PROVIDER)}`)
  lines.push(`sandbox_mode = ${tomlString(CODEX_SANDBOX_MODE)}`)
  lines.push(`approval_policy = ${tomlString(CODEX_APPROVAL_POLICY)}`)
  lines.push('')

  // --- Features
  lines.push('[features]')
  lines.push('codex_hooks = true')
  lines.push('multi_agent = true')
  lines.push('plugins = true')
  lines.push('')

  // --- Shell environment
  lines.push('[shell_environment_policy]')
  lines.push('inherit = "all"')
  lines.push('')

  // --- Sandbox workspace-write tuning
  lines.push('[sandbox_workspace_write]')
  lines.push('network_access = false')
  lines.push('exclude_slash_tmp = false')
  lines.push('')

  // --- MCP servers
  lines.push('# MCP servers — substituted at activation time.')
  lines.push('[mcp_servers.ref]')
  lines.push(`url = ${tomlString('https://api.ref.tools/mcp')}`)
  lines.push(`bearer_token_env_var = ${tomlString('REF_API_KEY')}`)
  lines.push('startup_timeout_sec = 20')
  lines.push('')

  // --- Hooks
  lines.push('# Hooks — translated from config/quality/src/hooks/codex-definitions.ts.')
  for (const event of ALL_CODEX_HOOK_EVENTS) {
    const groups = CODEX_HOOK_DEFINITIONS[event]
    if (groups === undefined || groups.length === 0) continue
    const block = emitHookBlocks(event, groups)
    if (block.length > 0) lines.push(block)
  }

  // --- Agents (subagent runtime caps)
  lines.push('[agents]')
  lines.push('max_threads = 6')
  lines.push('max_depth = 1')
  lines.push('job_max_runtime_seconds = 1800')
  lines.push('')

  // --- Built-in agent definitions are loaded from ~/.agents/agents/*.toml
  //     (symlinked by codex.nix). Listed here as a stable reference.
  lines.push('# Subagents discovered from ~/.agents/agents/*.toml:')
  lines.push('#   - architect (config/claude-code/agents/architect.toml)')
  lines.push('')

  // --- History
  lines.push('[history]')
  lines.push('max_bytes = 10485760')
  lines.push('')

  // --- TUI
  lines.push('[tui]')
  lines.push(`file_opener = ${tomlString('vscode')}`)
  lines.push('')

  return lines.join('\n')
}

export const generateCodexConfigFile = (outDir: string) =>
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem
    const content = generateConfigToml()
    const filePath = path.join(outDir, 'config.toml')
    yield* fs.writeFileString(filePath, content)
    yield* Effect.log(`Generated: ${filePath}`)
    return filePath
  })
