##############################
# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
# "$schema" = "https://yazi-rs.github.io/schemas/keymap.json"
##############################

[search]
# Fuzzy search works well with M-chip performance
fuzzy = true
incsearch = true   # Incremental search
smart_case = true
wrap_around = true # Wrap-around search (matches macOS UI patterns)

#################################
#  Manager key mappings
#################################

[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = "<C-d>"
run = "plugin diff"
desc = "Diff the selected with the hovered file"

[[mgr.prepend_keymap]]
on = "f"
run = "plugin jump-to-char"
desc = "Jump to char"

[[mgr.prepend_keymap]]
on = ["b", "a"]
run = "plugin mactag add"
desc = "Tag selected files"

[[mgr.prepend_keymap]]
on = ["b", "r"]
run = "plugin mactag remove"
desc = "Untag selected files"

# disk mount / unmount
[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'

[[mgr.prepend_keymap]]
on = "k"
run = "plugin --sync arrow --args=-1"

[[mgr.prepend_keymap]]
on = "j"
run = "plugin --sync arrow --args=1"

[[mgr.prepend_keymap]]
on = "K"
run = "plugin --sync parent-arrow --args=-1"

[[mgr.prepend_keymap]]
on = "J"
run = "plugin --sync parent-arrow --args=1"

[[mgr.prepend_keymap]]
on = "y"
run = ['''
shell 'echo "$@" | xclip -i -selection clipboard -t text/uri-list' --confirm
''', "yank"]

# cd back to the root of the current Git repository
[[mgr.prepend_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "cd back to git root"

[[mgr.prepend_keymap]]
on = "l"
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "p"
run = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

#############
# Bookmarks
#############

[[mgr.prepend_keymap]]
on = ["m"]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = ["'"]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = ["b", "d"]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = ["b", "D"]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

###################
# Misc
###################

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "ENTER the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on = ["g", "c"]
run = "plugin vcs-files"
desc = "Show Git file changes"

[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
on = "p"
run = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[mgr.prepend_keymap]]
on = "y"
run = [
  'shell -- echo "$@" | xclip -i -selection clipboard -t text/uri-list',
  "yank",
]

[[mgr.prepend_keymap]]
on = ["m"]
run = "plugin relative-motions"
desc = "Trigger a new relative motion"

#####################
# Projects
#####################

[[mgr.prepend_keymap]]
on = ["P", "s"]
run = "plugin projects save"
desc = "Save current project"

[[mgr.prepend_keymap]]
on = ["P", "l"]
run = "plugin projects load"
desc = "Load project"

[[mgr.prepend_keymap]]
on = ["P", "P"]
run = "plugin projects load_last"
desc = "Load last project"

[[mgr.prepend_keymap]]
on = ["P", "d"]
run = "plugin projects delete"
desc = "Delete project"

[[mgr.prepend_keymap]]
on = ["P", "D"]
run = "plugin projects delete_all"
desc = "Delete all projects"

[[mgr.prepend_keymap]]
on = ["P", "m"]
run = "plugin projects 'merge current'"
desc = "Merge current tab to other projects"

[[mgr.prepend_keymap]]
on = ["P", "M"]
run = "plugin projects 'merge all'"
desc = "Merge current project to other projects"

# Save the last project when exiting
[[mgr.prepend_keymap]]
on = ["q"]
run = "plugin projects quit"
desc = "Save last project and exit the process"

################
# Compress
################
[[mgr.prepend_keymap]]
on = ["c", "a"]
run = "plugin compress"
desc = "Archive selected files"

################
# Rsync
################
[[mgr.prepend_keymap]]
on = "R"
run = "plugin rsync"
desc = "Copy files using rsync"

[[mgr.prepend_keymap]]
on = "R"
run = "plugin rsync --args='user@server.com'"
desc = "Copy files using rsync to default location"

################
# Git / Lazygit
################
[[mgr.prepend_keymap]]
on = ["g", "i"]
run = "plugin lazygit"
desc = "run lazygit"

########################
# File size calculation
########################
[[mgr.prepend_keymap]]
on = [".", "s"]
run = "plugin what-size"
desc = "Calc size of selection or cwd"

[[mgr.prepend_keymap]]
on = "<A-y>"
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

##############################
# Open with command
##############################
[[mgr.prepend_keymap]]
on = "o"
run = "plugin open-with-cmd --args=block"
desc = "Open with command in the terminal"

[[mgr.prepend_keymap]]
on = "O"
run = "plugin open-with-cmd"
desc = "Open with command"

##################################
# Open shell in current directory
##################################
[[mgr.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

# ==================================================
# Input Configuration (Apple keyboard friendly)
# ==================================================

[input]
cd_shortcuts = true   # OS X-style key handling
dial_as_in_vim = true # macOS-style history
history_dedup = 10000 # Number of command-history entries

# Esc cancels input (only 1 press)
[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"
