# style name or JSON path (default "auto")
style: "auto"
# mouse support (TUI-mode only)
mouse: true
# use pager to display markdown
# pager: true
# word-wrap at width
width: 120
# show all files, including hidden and ignored.
all: true
