# Atuin configuration optimized for macOS Apple Silicon
# See https://atuin.sh/docs/config

# Database storage locations
# macOS paths for Apple Silicon
db_path = "~/.local/share/atuin/history.db"
key_path = "~/.local/share/atuin/key"
session_path = "~/.local/share/atuin/session"

# Date format used when displaying timestamps
# Using US format (month/day/year)
dialect = "us"

# Default timezone to use when displaying time
# Use the system's current local timezone
timezone = "local"

# Enable automatic sync with faster interval on Apple Silicon
# M-series chips can handle more frequent syncing with less impact
auto_sync = true
sync_frequency = "300"  # 5 minutes, Apple Silicon can handle this well

# Enable automatic update checks
update_check = true

# Address of the sync server
sync_address = "https://api.atuin.sh"

# Search mode - fuzzy works best with M-series performance
search_mode = "fuzzy"

# Filter mode to determine which history items to show
# global: show history from all sessions/hosts
filter_mode = "global"

# Enable workspace filtering (within git repositories)
# Great for developers on macOS
workspaces = true

# Use same filter mode for shell up-key binding
filter_mode_shell_up_key_binding = "global"

# Search mode for shell up-key binding
# Fuzzy works well with M-chip performance
search_mode_shell_up_key_binding = "fuzzy"

# Style for the history menu - auto adapts to terminal size
# Use full style on larger retina displays
style = "full"

# Maximum number of lines the interface should take up
# Set it to 0 to always go full screen
# Works well with larger Retina displays
inline_height = 0

# Put the search UI on the top (better for Retina displays)
invert = true

# Show a preview of the selected command
# Great for seeing long commands on wide displays
show_preview = true

# Behavior when escape key is pressed when searching
# return-original: return to the original command you were typing
exit_mode = "return-original"

# Word jump mode (for Cmd+left/right)
# emacs mode works better with macOS keyboard shortcuts
word_jump_mode = "emacs"

# Characters that count as a part of a word
word_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

# Number of context lines to show when scrolling by pages
# Higher on high-resolution displays
scroll_context_lines = 2

# Use ctrl instead of alt for numerical UI shortcuts
# This works better with macOS keyboard layout
ctrl_n_shortcuts = true

# Default history list format
# Added duration for better performance analysis
history_format = "{time}\t{command}\t{duration}"

# Prevent commands matching any of these regexes from being written to history
# Security focused for macOS developers
history_filter = [
  # AWS keys and tokens
  ".*AWS_.*KEY.*=.+",
  ".*aws_.*key.*=.+",
  ".*--access-key.*=.+",
  ".*--secret-key.*=.+",
  
  # GitHub tokens
  ".*GH_TOKEN.*=.+",
  ".*GITHUB_TOKEN.*=.+",
  ".*ghp_[A-Za-z0-9]{36}.*",
  ".*github_pat_[A-Za-z0-9]{22}_[A-Za-z0-9]{59}.*",
  
  # API keys and tokens
  ".*api[_-]?key.*=.+",
  ".*token.*=.+",
  ".*password.*=.+",
  ".*secret.*=.+",
  
  # Common MacOS credential managers
  ".*security find-generic-password.*",
  ".*keychain-access.*",
  
  # Common explicit patterns
  "^\\s*curl\\s+.+(-u|--user)\\s+[^\\s:]+:[^\\s]+\\s*.*$"
]

# Prevent commands run in directories containing secrets
cwd_filter = [
  "^/Users/[^/]+/.ssh",
  "^/Users/[^/]+/\\.aws",
  "^/Users/[^/]+/\\.config/gcloud",
  "^/Users/[^/]+/\\.gnupg",
  "^/Users/[^/]+/\\.kube",
  "^/Users/[^/]+/\\.terraform",
  "^/private/",
  "^.+/secrets?/?.*$",
  "^.+/credential.*$"
]

# Configure the maximum height of the preview to show
# Adjusted for Retina displays
max_preview_height = 6

# Show help info (with version check)
show_help = true

# Show tabs for search and inspect
show_tabs = true

# Enable secrets filtering (AWS keys, GitHub tokens, etc)
secrets_filter = true

# Immediately execute command on Enter
# Better UX for macOS users
enter_accept = true

# Set keymap mode to emacs (macOS default)
keymap_mode = "emacs"

# Adjust cursor style for better visibility on Retina displays
# In TOML, inline tables must be on a single line
keymap_cursor = { emacs = "blink-block", vim_insert = "blink-bar", vim_normal = "steady-block" }

# Network settings adjusted for better performance on high-speed connections
network_connect_timeout = 3
network_timeout = 5

# Timeout for acquiring a local database connection
# Faster on Apple Silicon
local_timeout = 3

# Reduced motion mode for accessibility
# Set to false for standard animations on M-series
prefers_reduced_motion = false

# Enhanced statistics mode
[stats]
# Commands where we should consider the subcommand for statistics
# Example: "git commit" instead of just "git"
common_subcommands = [
  # Standard Linux/Unix tools
  "apt", "cargo", "dnf", "docker", "git", "go", "kubectl", "nix", "npm", "pnpm", "systemctl", "tmux", "yarn",
  
  # macOS specific tools
  "brew", "xcodebuild", "swift", "xcrun", "defaults", "mas", "open", "launchctl", "diskutil",
  
  # Development tools common on macOS
  "pod", "fastlane", "flutter", "xed"
]

# Commands to strip from statistics
common_prefix = ["sudo", "env", "time", "nice"]

# Commands to completely ignore from statistics
ignored_commands = [
  "cd", "ls", "ll", "la", "pwd", "clear", "cls", "exit", "history",
  # macOS specific
  "open", "pbcopy", "pbpaste", "defaults", "osascript"
]

[keys]
# Allow cursor keys to exit when at top/bottom of history
scroll_exits = false

[sync]
# Enable sync v2 by default
records = true

[preview]
# Preview calculation strategy
# Use auto to dynamically adjust based on command length
strategy = "auto"

[daemon]
# Enable the sync daemon (more efficient on M-series)
enabled = true

# How often the daemon should sync (in seconds)
sync_frequency = 300

# Path to the unix socket (macOS specific)
socket_path = "~/.local/share/atuin/atuin.sock"

# TCP port for non-unix systems
tcp_port = 8889
