/**
 * Settings Generator (Effect-TS Native)
 *
 * Generates complete Claude Code settings.json.
 * Reads plugins/marketplaces from Nix-generated nix-config.json.
 *
 * SSOT: modules/home/apps/claude.nix → generated/nix-config.json → settings.json
 */

import { FileSystem } from '@effect/platform'
import * as path from 'node:path'
import { Effect } from 'effect'
import { HOOK_DEFINITIONS } from '../../hooks/definitions'

// =============================================================================
// Permissions SSOT
// =============================================================================

const PERMISSIONS = {
  allow: [
    'Read',
    'Grep(*)',
    'Glob(*)',
    'WebSearch',

    'Bash(ls:*)',
    'Bash(cat:*)',
    'Bash(head:*)',
    'Bash(tail:*)',
    'Bash(find:*)',
    'Bash(fd:*)',
    'Bash(rg:*)',
    'Bash(grep:*)',
    'Bash(wc:*)',
    'Bash(which:*)',
    'Bash(echo:*)',
    'Bash(pwd)',
    'Bash(mkdir:*)',
    'Bash(cp:*)',
    'Bash(mv:*)',
    'Bash(rm:*)',
    'Bash(touch:*)',
    'Bash(tree:*)',
    'Bash(eza:*)',
    'Bash(bat:*)',
    'Bash(delta:*)',
    'Bash(sort:*)',
    'Bash(uniq:*)',
    'Bash(jq:*)',
    'Bash(curl:*)',
    'Bash(open:*)',
    'Bash(readlink:*)',
    'Bash(xargs:*)',
    'Bash(sh:*)',

    'Bash(git:*)',
    'Bash(GIT_PAGER=cat git:*)',
    'Bash(gh:*)',

    'Bash(pnpm:*)',
    'Bash(npm:*)',
    'Bash(npx:*)',
    'Bash(node:*)',
    'Bash(python:*)',
    'Bash(python3:*)',
    'Bash(uv:*)',
    'Bash(uvx:*)',
    'Bash(pipx:*)',
    'Bash(ruff:*)',
    'Bash(pytest:*)',
    'Bash(bun:*)',
    'Bash(tsx:*)',
    'Bash(copier:*)',
    'Bash(just:*)',
    'Bash(make:*)',
    'Bash(cargo:*)',

    'Bash(biome:*)',
    'Bash(oxlint:*)',
    'Bash(vitest:*)',
    'Bash(tsc:*)',
    'Bash(playwright:*)',

    'Bash(docker:*)',
    'Bash(docker-compose:*)',
    'Bash(pulumi:*)',
    'Bash(esc:*)',
    'Bash(wrangler:*)',
    'Bash(kubectl:*)',
    'Bash(terraform:*)',

    'Bash(nix:*)',
    'Bash(nix-shell:*)',
    'Bash(darwin-rebuild:*)',
    'Bash(home-manager:*)',
    'Bash(sudo darwin-rebuild:*)',
    'Bash(alejandra:*)',
    'Bash(nixfmt:*)',
    'Bash(shfmt:*)',
    'Bash(stylua:*)',

    'Bash(ps:*)',
    'Bash(pgrep:*)',
    'Bash(killall:*)',
    'Bash(launchctl:*)',
    'Bash(sudo launchctl:*)',
    'Bash(defaults read:*)',
    'Bash(osascript:*)',
    'Bash(sw_vers:*)',
    'Bash(mdfind:*)',
    'Bash(infocmp:*)',

    'Bash(sqlite3:*)',
    'Bash(tree-sitter:*)',
    'Bash(tldr:*)',
    'Bash(fc-list:*)',
    'Bash(nvim:*)',
    'Bash(ghostty:*)',
    'Bash(zellij:*)',
    'Bash(claude:*)',

    'Write(*)',
    'Edit(*)',

    'WebFetch(domain:github.com)',
    'WebFetch(domain:raw.githubusercontent.com)',
    'WebFetch(domain:gist.github.com)',
    'WebFetch(domain:gist.githubusercontent.com)',
    'WebFetch(domain:docs.anthropic.com)',
    'WebFetch(domain:effect.website)',
    'WebFetch(domain:ghostty.org)',
    'WebFetch(domain:zellij.dev)',
    'WebFetch(domain:www.lazyvim.org)',
    'WebFetch(domain:macos-defaults.com)',
    'WebFetch(domain:apps.apple.com)',

    'mcp__ref__*',
    // REMOVED: mcp__exa__* (January 2026 MINIMAL)
  ],
  deny: [
    'Read(**/.env*)',
    'Read(**/secrets*)',
    'Read(**/*.pem)',
    'Read(**/*.key)',
    'Read(**/.ssh/*)',
    'Read(**/.gnupg/*)',
    'Read(**/.netrc)',
    'Write(**/.env*)',
    'Write(**/.git/*)',
    'Edit(**/.git/*)',
    'Bash(rm -rf /)',
    'Bash(rm -rf ~)',
    'Bash(sudo rm -rf:*)',
    'Bash(chmod 777:*)',
    'Bash(git push --force:*)',
    'Bash(git reset --hard:*)',
  ],
} as const

// =============================================================================
// Settings Type
// =============================================================================

type ClaudeSettings = {
  readonly $schema: string
  readonly $comment: string
  readonly model: string
  readonly cleanupPeriodDays: number
  readonly attribution: { readonly commit: string; readonly pr: string }
  readonly alwaysThinkingEnabled: boolean
  readonly verbose: boolean
  readonly env: Readonly<Record<string, string>>
  readonly permissions: typeof PERMISSIONS
  readonly hooks: typeof HOOK_DEFINITIONS
}

// =============================================================================
// Generator
// =============================================================================

const CLAUDE_MODEL = 'opus' as const

const generateSettings = (): ClaudeSettings => ({
  $schema: 'https://json.schemastore.org/claude-code-settings.json',
  $comment: 'Generated by Quality System. Do not edit manually.',
  model: CLAUDE_MODEL,
  cleanupPeriodDays: 7,
  attribution: { commit: '', pr: '' },
  alwaysThinkingEnabled: true,
  verbose: false,
  env: { MAX_THINKING_TOKENS: '31999' },
  permissions: PERMISSIONS,
  hooks: HOOK_DEFINITIONS,
})

export const generateSettingsFile = (outDir: string) =>
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem

    const settings = generateSettings()
    const filePath = path.join(outDir, 'settings.json')

    yield* fs.writeFileString(filePath, JSON.stringify(settings, null, 2))

    yield* Effect.log(`Generated: ${filePath}`)
    return filePath
  })
