-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set:
-- https://www.lazyvim.org/configuration/general#keymaps
-- https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
