#!/usr/bin/env zsh

# Orig Hank

#-------------------------------------------------------------------------------
# TODO: below
#-------------------------------------------------------------------------------

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

# export TERM='rxvt-256color'
# # export DOTFILES="$HOME/.dotfiles"
# export DOTFILES="$HOME/src/dotfiles"
# # export WORKSPACE="$HOME/workspace"
# export WORKSPACE="$HOME/src"

# [ -f "$DOTFILES/install_config" ] && source "$DOTFILES/install_config"

# # XDG
# export XDG_CONFIG_HOME=$HOME/.config
# export XDG_DATA_HOME=$XDG_CONFIG_HOME/local/share
# export XDG_CACHE_HOME=$XDG_CONFIG_HOME/cache

# # editor
# export EDITOR="nvim"
# export VISUAL="nvim"

# # zsh
# export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
# export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
# export HISTSIZE=10000                   # Maximum events for internal history
# export SAVEHIST=10000                   # Maximum events in history file

# # # other software
# # export TMUXP_CONFIGDIR="$XDG_CONFIG_HOME/tmuxp"
# # export COMPOSER_HOME="$XDG_CONFIG_HOME/composer"
# # export I3_CONFIG="$XDG_CONFIG_HOME/i3"
# export VIMCONFIG="$XDG_CONFIG_HOME/nvim"
# # export GIMP_VERSION="2.10"
# # export SCREENSHOT="$HOME/Documents/images/screenshots"

# # Man pages
# export MANPAGER='nvim +Man!'


# # fzf
# export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git"'
# export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# FZF_COLORS="bg+:-1,\
# fg:gray,\
# fg+:white,\
# border:black,\
# spinner:0,\
# hl:yellow,\
# header:blue,\
# info:green,\
# pointer:red,\
# marker:blue,\
# prompt:gray,\
# hl+:red"

# export FZF_DEFAULT_OPTS="--height 60% \
# --border sharp \
# --layout reverse \
# --color '$FZF_COLORS' \
# --prompt '∷ ' \
# --pointer ▶ \
# --marker ⇒"
# export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -n 10'"
# export FZF_COMPLETION_DIR_COMMANDS="cd pushd rmdir tree ls"

# # export FZF_TMUX_OPTS="-p"
