---
# LLM Models Configuration - 2025 (May)
# Includes current capabilities, version information, and API settings

# Claude Models
claude:
  versions:
    - id: "claude-3-7-sonnet-20250219"
      name: "Claude 3.7 Sonnet"
      released: "2025-02-19"
      context_window: 200000
      recommended_for:
        - "General programming tasks"
        - "Code review and enhancement"
        - "Data exploration and analysis"
      strengths:
        - "Strong contextual understanding"
        - "Excellent code generation"
        - "Natural communication style"
    - id: "claude-3-opus-20240229"
      name: "Claude 3 Opus"
      released: "2024-02-29"
      context_window: 200000
      recommended_for:
        - "Complex reasoning tasks"
        - "In-depth research analysis"
        - "Multi-step problem solving"
      strengths:
        - "Advanced reasoning"
        - "Nuanced understanding"
        - "High accuracy in complex domains"
    - id: "claude-3-haiku-20240307"
      name: "Claude 3 Haiku"
      released: "2024-03-07"
      context_window: 200000
      recommended_for:
        - "Quick drafts and ideas"
        - "Simple code generation"
        - "Rapid responses for iterative work"
      strengths:
        - "Fast response time"
        - "Efficient operation"
        - "Low token usage"
  api_settings:
    endpoint: "https://api.anthropic.com/v1/messages"
    auth_type: "bearer"
    env_var: "ANTHROPIC_API_KEY"
    rate_limit: 50

# OpenAI Models
openai:
  versions:
    - id: "gpt-4-turbo-2024-04-09"
      name: "GPT-4 Turbo (April 2024)"
      released: "2024-04-09"
      context_window: 128000
      recommended_for:
        - "Complex coding tasks"
        - "Multi-language translation"
        - "Tool augmentation"
      strengths:
        - "Strong at following specific instructions"
        - "Excellent tool usage capabilities"
        - "Advanced code generation"
    - id: "gpt-3.5-turbo-0125"
      name: "GPT-3.5 Turbo"
      released: "2024-01-25"
      context_window: 16385
      recommended_for:
        - "Simple code tasks"
        - "Quick drafts"
        - "Casual usage"
      strengths:
        - "Cost-effective"
        - "Fast responses"
        - "Good for many routine tasks"
  api_settings:
    endpoint: "https://api.openai.com/v1/chat/completions"
    auth_type: "bearer"
    env_var: "OPENAI_API_KEY"
    rate_limit: 60

# Google Gemini Models
gemini:
  versions:
    - id: "gemini-pro"
      name: "Gemini Pro"
      released: "2023-12-13"
      context_window: 32768
      recommended_for:
        - "General coding tasks"
        - "Document analysis"
        - "Information synthesis"
      strengths:
        - "Strong at structured reasoning"
        - "Good performance/cost ratio"
        - "Solid with factual information"
    - id: "gemini-1.5-pro"
      name: "Gemini 1.5 Pro"
      released: "2024-05-01"
      context_window: 1000000
      recommended_for:
        - "Long context processing"
        - "Multi-modal reasoning"
        - "Code generation with context"
      strengths:
        - "Massive context window"
        - "Improved multi-modal capabilities"
        - "Better code understanding"
  api_settings:
    endpoint: "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent"
    auth_type: "apikey"
    env_var: "GOOGLE_API_KEY"
    rate_limit: 60

# Open Source Models
opensource:
  versions:
    - id: "mixtral-8x7b-32768"
      name: "Mixtral 8x7B 32K"
      released: "2023-12-15"
      context_window: 32768
      recommended_for:
        - "Local code generation"
        - "Privacy-sensitive tasks"
        - "Offline development"
      strengths:
        - "Can run locally"
        - "No data sharing concerns"
        - "Large context window"
    - id: "llama-3-70b-instruct"
      name: "Llama 3 70B Instruct"
      released: "2024-04-18"
      context_window: 8192
      recommended_for:
        - "Advanced local reasoning"
        - "Code completion"
        - "Technical documentation"
      strengths:
        - "Strong performance for size"
        - "Good at following instructions"
        - "Active community support"
  api_settings:
    endpoint: "http://localhost:11434/api/generate" # Assuming using Ollama
    auth_type: "none"
    env_var: ""
    rate_limit: null  # Local deployment

# Task-specific model recommendations
task_recommendations:
  code_generation:
    first_choice: "claude-3-7-sonnet-20250219"
    alternative: "gpt-4-turbo-2024-04-09"
    local_option: "llama-3-70b-instruct"
  code_review:
    first_choice: "claude-3-opus-20240229"
    alternative: "gpt-4-turbo-2024-04-09"
    local_option: "mixtral-8x7b-32768"
  documentation:
    first_choice: "claude-3-7-sonnet-20250219"
    alternative: "gemini-1.5-pro"
    local_option: "llama-3-70b-instruct"
  quick_assistance:
    first_choice: "claude-3-haiku-20240307"
    alternative: "gpt-3.5-turbo-0125"
    local_option: "mixtral-8x7b-32768"
  large_codebase_analysis:
    first_choice: "gemini-1.5-pro"
    alternative: "claude-3-opus-20240229"
    local_option: null  # Not recommended locally

# Function calling capabilities (1-5 scale)
function_calling:
  "claude-3-7-sonnet-20250219": 5
  "claude-3-opus-20240229": 5
  "claude-3-haiku-20240307": 4
  "gpt-4-turbo-2024-04-09": 5
  "gpt-3.5-turbo-0125": 4
  "gemini-pro": 3
  "gemini-1.5-pro": 4
  "mixtral-8x7b-32768": 2
  "llama-3-70b-instruct": 3