#!/usr/bin/env zsh

# -----------------------------------------------------
# Early Environment Setup (loaded for all shell types)
# -----------------------------------------------------

# XDG Base Directory Specification
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"

# Ensure XDG directories exist
mkdir -p "$XDG_CONFIG_HOME" "$XDG_CACHE_HOME" "$XDG_DATA_HOME" "$XDG_STATE_HOME"

# Set ZDOTDIR to point to our dotfiles location
export ZDOTDIR="${HOME}/dotfiles/home/zsh"

# Core paths (minimal set needed before zshrc)
export PATH="/opt/homebrew/bin:$PATH"
[[ -d "$HOME/.local/bin" ]] && export PATH="$HOME/.local/bin:$PATH"

# Basic environment settings
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Editor settings
export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="less"
