# Warp Terminal Keybindings
# Optimized for macOS Apple Silicon (2025)
# https://docs.warp.dev/features/keybindings

# ============================
# Workspace Management
# ============================

# Disable unused a11y verbosity controls
"workspace:set_a11y_concise_verbosity_level": none
"workspace:set_a11y_verbose_verbosity_level": none

# Environment variables management - matches macOS standards
"workspace:create_personal_env_vars": cmd-e

# Settings shortcuts - macOS convention
"workspace:show_settings_features_page": "cmd-,"
"workspace:show_settings_keyboard_shortcuts_page": "ctrl-,"

# Command palette - optimized for developers on macOS
"workspace:toggle_command_palette": cmd-k

# ============================
# Editor Interactions
# ============================

# Autosuggestion handling - improved for Apple Silicon performance
"editor_view:insert_autosuggestion": tab
"input:open_completion_suggestions": tab

# Terminal clear actions - standard macOS shortcuts
"editor_view:clear_lines": shift-cmd-R
"terminal:clear_blocks": cmd-r

# Disable unused editor features
"editor_view:strikethrough": none

# ============================
# Pane Management
# ============================

# Pane organization (disable defaults to use custom ones)
"pane_group:add_left": none
"pane_group:add_up": none

# ============================
# Navigation Bindings
# ============================

# This makes vim-style navigation work better in Warp
# These are optimized for Apple keyboards

# Move up and down in completion menu - vim style
"selectNextSuggestion": ctrl-j
"selectPreviousSuggestion": ctrl-k
"acceptSelectedSuggestion": ctrl-l

# Move up and down in file browser - vim style
"file-browser.stepOut": ctrl-h
"file-browser.stepIn": ctrl-l

# ============================
# Custom M-series Optimizations
# ============================

# History navigation shortcuts (faster with M-series)
"history:search_history": cmd-r

# Block management
"blocks:toggle_details": ctrl-d
"blocks:collapse_all": ctrl-shift-[
"blocks:expand_all": ctrl-shift-]
"blocks:select_all": cmd-a

# Smart shell navigation
"shell:open_in_finder": cmd-shift-f
"shell:clear_all": cmd-k ctrl-k

# ============================
# Apple Silicon Specific Terminal Actions
# ============================

# Better tab management for wide-screen Apple displays
"tabs:select_next_tab": cmd-shift-]
"tabs:select_previous_tab": cmd-shift-[

# Smart block search
"search:start_search": cmd-f
"search:close_search": esc

# Better syntax highlighting
"editor_view:toggle_syntax_highlighting": cmd-shift-h

# Shared clipboard operations - optimized for macOS
"terminal:copy_selection": cmd-c
"terminal:paste_from_clipboard": cmd-v

# ============================
# End of Configuration
# ============================
