---
"shell:open_in_finder": cmd-shift-f
"editor_view:clear_lines": shift-cmd-R
"editor_view:toggle_syntax_highlighting": cmd-shift-h
"blocks:expand_all": "ctrl-shift-]"
acceptSelectedSuggestion: ctrl-l
"pane_group:add_up": none
file-browser.stepIn: ctrl-l
selectPreviousSuggestion: ctrl-k
"workspace:set_a11y_concise_verbosity_level": none
"history:search_history": cmd-r
"pane_group:add_left": none
file-browser.stepOut: ctrl-h
"workspace:show_settings_features_page": "cmd-,"
"shell:clear_all": cmd-k ctrl-k
"blocks:select_all": cmd-a
"tabs:select_previous_tab": "cmd-shift-["
"tabs:select_next_tab": "cmd-shift-]"
"search:close_search": esc
"workspace:toggle_command_palette": cmd-k
"blocks:toggle_details": ctrl-d
"editor_view:strikethrough": none
"workspace:set_a11y_verbose_verbosity_level": none
"search:start_search": cmd-f
"terminal:clear_blocks": cmd-r
selectNextSuggestion: ctrl-j
"input:open_completion_suggestions": tab
"workspace:show_settings_keyboard_shortcuts_page": "ctrl-,"
"terminal:copy_selection": cmd-c
"blocks:collapse_all": "ctrl-shift-["
"workspace:create_personal_env_vars": cmd-e
"terminal:paste_from_clipboard": cmd-v
