#!/usr/bin/env bash

# Load path utilities
[[ -f "$HOME/.config/shell/path_utils.sh" ]] && source "$HOME/.config/shell/path_utils.sh"

. "$HOME/.atuin/bin/env"
# [[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh
eval "$(atuin init bash)"

# load all completions
if [ -d ~/.bash_completion.d ]; then
    for f in ~/.bash_completion.d/*.sh; do
        [ -r "$f" ] && . "$f"
    done
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# <ant-setup>
# This was generated by ant-setup, feel free to remove it
eval "\$(direnv hook bash)"
# </ant-setup>

if [ -n "$IN_NIX_SHELL" ]; then
    # We're in a nix-shell or nix develop
    source "${cf:-$HOME/dotfiles/config}/nix/.bashrc.nix-shell"
fi
