matches:
  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # Simple text replacement
  - trigger: ";es"
    replace: "espanso"

  - trigger: ";home"
    replace: "30 Ridge Square NW Apt 621, Washington, DC 20016"

  - trigger: ";home-zip"
    replace: "20016"

  - trigger: ";sig"
    replace: "Best, Hank"
