openapi: 3.0.0
info:
  title: Noggin PDF API
  version: 0.1.1

paths:
  /stem:
    post:
      summary: Create a new stem
      operationId: createStem
      parameters:
        - name: stemId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              binaryFormat: base64

      responses:
        "201":
          description: PDFs accepted for processing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Stem"
  /stems/{stemId}/pdfs:
    post:
      summary: Upload one or more PDFs for processing
      operationId: uploadPdfs
      parameters:
        - name: stemId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [pdfs]
              properties:
                pdfs:
                  type: array
                  items:
                    $ref: "#/components/schemas/Pdf"
      responses:
        "201":
          description: PDFs accepted for processing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Stem"

  /stems/{stemId}/pdfs/{pdfId}:
    get:
      summary: Get processing metadata for a single PDF
      operationId: getPdfMetadata
      parameters:
        - name: stemId
          in: path
          required: true
          schema:
            type: string
        - name: pdfId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: PDF metadata
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pdf"

  /stems/{stemId}/pdfs/{pdfId}/extract:
    get:
      summary: Get extracted content from a processed PDF
      operationId: getPdfExtract
      parameters:
        - name: stemId
          in: path
          required: true
          schema:
            type: string
        - name: pdfId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Extraction result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Extract"

components:
  schemas:
    Stem:
      type: object
      required: [id]
      properties:
        id:
          type: string
        pdfs:
          type: array
          items:
            $ref: "#/components/schemas/Pdf"
        metadata:
          $ref: "#/components/schemas/PdfMetadata"

    ProcessingStatus:
      type: string
      enum: [queued, processing, ready, failed]

    Pdf:
      type: object
      required: [id, stemId, filename, stage]
      description: Logical PDF record within Noggin.
      properties:
        id:
          type: string
        stemId:
          type: string
        filename:
          type: string
        pages:
          type: integer
          minimum: 1
        createdAt:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time
          nullable: true
        status:
          $ref: "#/components/schemas/ProcessingStatus"
        processorId:
          type: string
        metadata:
          $ref: "#/components/schemas/PdfMetadata"

    Extract:
      type: object
      required: [pdfId, extractBlocks]
      properties:
        pdfId:
          type: string
        extractBlocks:
          type: array
          items:
            $ref: "#/components/schemas/ExtractBlock"
        metadata:
          type: object
          additionalProperties: true

    ExtractBlock:
      type: object
      required: [text]
      properties:
        id:
          type: string
        extractId:
          type: string
        text:
          type: string
        page:
          type: integer
          minimum: 1
        bbox:
          type: array
          description: Bounding box [x0, y0, x1, y1] in PDF points
          minItems: 4
          maxItems: 4
          items:
            type: number
        confidence:
          type: number
          minimum: 0
          maximum: 1
        metadata:
          type: object
          additionalProperties: true
